- platform: group
  name: "Bedroom Lights"
  entities:
    - light.tradfri_bulb_e27_cws_opal_600lm
    - light.bed_lights
    - light.stringlights

- platform: "group"
  name: "Living Room Lights"
  entities:
    - light.tradfri_bulb_e27_opal_1000lm
    - light.christmas_tree
