- platform: mqtt
  name: 'Bedroom Stringlights'
  command_topic: !secret mqtt_topic_bedroom_stringlights

- platform: mqtt
  name: 'Desk spots'
  command_topic: !secret mqtt_topic_desk_spots

- platform: mqtt
  name: 'Server Ledstrips'
  command_topic: !secret mqtt_topic_server_ledstrips

- platform: mqtt
  name: 'Bed Lights'
  command_topic: !secret mqtt_topic_bed_lights

- platform: mqtt
  name: 'Desk light'
  command_topic: !secret mqtt_topic_desk_light
