# Tradfri proxies switches as lights
- platform: switch
  name: "Christmas Tree"
  entity_id: switch.tradfri_control_outlet_3
- platform: switch
  name: 'Stringlights'
  entity_id: switch.stringlights
- platform: switch
  name: "Bed lights"
  entity_id: switch.bed_lights
