- platform: template
  sensors:
    telenet_off_peak:
      friendly_name: "Telenet Off Peak"
      entity_id: sensor.time_date
      value_template: >-
        {{ now().hour >= 0 and now().hour < 12 }}
      icon_template: >-
        {% if now().hour >= 0 and now().hour < 12 %}
          mdi:arrow-bottom-right-thick
        {% else %}
          mdi:arrow-top-right-thick
        {% endif %}

    at_work:
      friendly_name: "At work"
      entity_id: device_tracker.thibaults_iphone
      entity_picture_template: >-
        {% if is_state("device_tracker.thibaults_iphone", "Werk Thib") %}
          /local/icons/itp-logo-active.svg
        {% else %}
          /local/icons/itp-logo-inactive.svg
        {% endif %}
      value_template: >-
        {{ is_state("device_tracker.thibaults_iphone", "Werk Thib") }}
