- platform: template
  sensors:
    # Waste collection
    waste_collection_carboard:
      friendly_name: "Cardboard collection"
      entity_id: sensor.day_of_week
      icon_template: mdi:package-variant
      value_template: >-
        {{ is_state("sensor.day_of_week", "Monday") }}
    waste_collection_trash:
      friendly_name: "Trash collection"
      entity_id: sensor.day_of_week
      icon_template: mdi:recycle
      value_template: >-
        {{ is_state("sensor.day_of_week", "Thursday") }}
    waste_collection_pmd:
      friendly_name: "PMD collection"
      entity_id: sensor.day_of_week
      icon_template: mdi:cup-water
      value_template: >-
        {{ is_state("sensor.day_of_week", "Monday") }}

    water_work_plants:
      friendly_name: "Watering day"
      entity_id: sensor.day_of_week
      icon_template: mdi:flower
      value_template: >-
        {{ is_state("sensor.day_of_week", "Thursday") }}

    at_work:
      friendly_name: "At work"
      entity_id: device_tracker.thibaults_iphone
      entity_picture_template: >-
        {% if is_state("device_tracker.thibaults_iphone", "Werk Thib") %}
          /local/icons/itp-logo-active.png
        {% else %}
          /local/icons/itp-logo-inactive.png
        {% endif %}
      value_template: >-
        {{ is_state("device_tracker.thibaults_iphone", "Werk Thib") }}
