- platform: tod
  name: "Working day hours"
  after: '07:30'
  before: '19:35'

#### DAY CYCLES ########################################################################
# Morning: 7AM -> 12PM
- platform: tod
  name: 'Morning'
  after: "07:00"
  before: "12:00"

# Late Morning: 9.30AM -> 12PM
- platform: tod
  name: "Late Morning"
  after: "09:30"
  before: "12:00"

# Noon: 12PM -> 6PM
- platform: tod
  name: 'Noon'
  after: "12:00"
  before: "18:00"

# Evening: Sunset -> 10PM
- platform: tod
  name: "Evening"
  after: sunset
  before: "22:00"

# Night: 10PM -> 7AM
- platform: tod
  name: 'Night'
  after: "22:00"
  before: "07:00"
