language: python
cache: pip
python:
  - '3.6'
install:
  - 'pip3 install homeassistant'
script:
  - 'mv secrets.test.yaml secrets.yaml'
  - 'hass -c . --script check_config | tee check.output'
  - '! less check.output | grep -q "Failed config"'
