homeassistant:
  name: !secret home_name
  latitude: !secret lat
  longitude: !secret long
  elevation: 0
  unit_system: 'metric'
  time_zone: 'Europe/Brussels'
  customize: !include customize.yaml

frontend:
  themes: !include_dir_merge_named themes/

cloud: !include_dir_merge_named components/cloud

logger:
  default: warn
  logs:
    custom_components.custom_updater: debug

config:
discovery:
media_extractor:
updater:
history:
logbook:
http:
  api_password: !secret http_password

mqtt:
  broker: !secret cloudmqtt_broker
  port: !secret cloudmqtt_port
  username: !secret cloudmqtt_user
  password: !secret cloudmqtt_pass

downloader:
  download_dir: '/share'

ios:
map:

wake_on_lan:

conversation:
tts:
  platform: 'google'

google:
  client_id: !secret google_calendar_client_id
  client_secret: !secret google_calendar_client_secret

sun:
weather:
  - platform: yweather
    name: 'Yahoo Weather'

weblink:
  entities: !include_dir_merge_list components/weblinks/

panel_iframe: !include_dir_merge_named components/panel_iframes/

twilio:
  account_sid: !secret twilio_account_sid
  auth_token: !secret twilio_auth_token

# Commented out for instability
# github.com/custom-components
# custom_updater:
# sickrage:
#   host: !secret sickrage_url_api
#   api_key: !secret sickrage_api_key

binary_sensor: !include_dir_merge_list components/binary_sensors/
camera: !include_dir_merge_list components/cameras/
device_tracker: !include_dir_merge_list components/device_trackers/
input_select: !include_dir_merge_named components/inputs/
light: !include_dir_merge_list components/lights/
media_player: !include_dir_merge_list components/media_players/
notify: !include_dir_merge_list components/notifications/
script: !include_dir_merge_named components/scripts/
sensor: !include_dir_merge_list components/sensors/
switch: !include_dir_merge_list components/switches/

automation: !include automations.yaml
group: !include_dir_merge_named groups/
scene: !include_dir_merge_list scenes/
zone: !include zones.yaml
