# region: Default config
homeassistant:
  packages: !include_dir_named packages/
  customize: !include customize.yaml

cloud:

frontend:
  themes: !include_dir_merge_named themes/
  javascript_version: latest

system_health:
updater:
logger:
  default: warn

config:
discovery:
ssdp:
zeroconf:
ios:
mobile_app:
map:
person:
wake_on_lan:
sun:

automation: !include automations.yaml
scene: !include scenes.yaml
script: !include scripts.yaml
# endregion

# region: History
history:
logbook:
  exclude:
    domains:
      - calendar
recorder:
  db_url: !secret maria_db_url
  purge_keep_days: 5
  exclude:
    domains:
      - calendar
    entities:
      - sensor.calendar_agenda
      - sensor.calendar_events
      - sensor.calendar_lot_thib
      - sensor.calendar_tasks

influxdb:
  host: !secret localhost
  database: home_assistant
  username: !secret influxdb_user
  password: !secret influxdb_password
  max_retries: 3
  default_measurement: state
  include:
    domains:
      - binary_sensor
      - light
      - sensor
      - person
# endregion

# region: 3rd party
tts:
  - platform: google_translate

hacs:
  token: !secret hacs_github_token
  sidepanel_title: HACS
  sidepanel_icon: "mdi:package"
  country: BE

google:
  client_id: !secret google_calendar_client_id
  client_secret: !secret google_calendar_client_secret

spotify:
  client_id: !secret spotify_id
  client_secret: !secret spotify_secret

octoprint:
  host: !secret rpi_node_fuse
  api_key: !secret octoprint_api_key
  port: 5000
  number_of_tools: 1
  bed: true
# endregion

# region: integrations
binary_sensor: !include_dir_merge_list integrations/binary_sensors/
camera: !include_dir_merge_list integrations/cameras/
input_boolean: !include integrations/inputs/boolean.yaml
light: !include_dir_merge_list integrations/lights/
media_player: !include_dir_merge_list integrations/media_players/
notify: !include_dir_merge_list integrations/notifications/
panel_iframe: !include_dir_merge_named integrations/panel_iframes
rest_command: !include_dir_merge_named integrations/rest_commands
sensor: !include_dir_merge_list integrations/sensors/
switch: !include_dir_merge_list integrations/switches/
weather: !include_dir_merge_list integrations/weather/
# endregion
