# region: Default config
homeassistant:
  customize: !include customize.yaml

cloud:

frontend:
  themes: !include_dir_merge_named themes/
  javascript_version: latest

system_health:
updater:
logger:
  default: warn

config:
discovery:
ssdp:
zeroconf:
mobile_app:
person:
wake_on_lan:
sun:
media_source:
image:

automation: !include automations.yaml
scene: !include scenes.yaml
script: !include scripts.yaml
# endregion

# region: History
history:
logbook:
  exclude:
    domains:
      - calendar
recorder:
  db_url: !secret maria_db_url
  purge_keep_days: 5
  exclude:
    domains:
      - calendar
    entities:
      - sensor.calendar_agenda
      - sensor.calendar_events
      - sensor.calendar_lot_thib
      - sensor.calendar_tasks
# endregion

# region: 3rd party
tts:
  - platform: google_translate

google:
  client_id: !secret google_calendar_client_id
  client_secret: !secret google_calendar_client_secret

spotify:
  client_id: !secret spotify_id
  client_secret: !secret spotify_secret

stream:
ffmpeg:

zigbee2mqtt_networkmap:

nzbget:
  host: !secret localhost
  username: !secret nzbget_username
  password: !secret nzbget_password
# endregion

# region: integrations
binary_sensor: !include_dir_merge_list integrations/binary_sensors/
camera: !include_dir_merge_list integrations/cameras/
input_boolean: !include integrations/inputs/boolean.yaml
input_datetime: !include integrations/inputs/datetime.yaml
input_select: !include integrations/inputs/select.yaml
light: !include_dir_merge_list integrations/lights/
media_player: !include_dir_merge_list integrations/media_players/
notify: !include_dir_merge_list integrations/notifications/
rest_command: !include_dir_merge_named integrations/rest_commands
sensor: !include_dir_merge_list integrations/sensors/
switch: !include_dir_merge_list integrations/switches/
weather: !include_dir_merge_list integrations/weather/
# endregion
