homeassistant:
  packages: !include_dir_named packages/
  customize: !include customize.yaml

cloud:
tts:
  - platform: google_translate

frontend:
  javascript_version: latest
  themes: !include_dir_merge_named themes/

hacs:
  token: !secret hacs_github_token
  sidepanel_title: HACS
  sidepanel_icon: "mdi:package"

system_health:
logger:
  default: warn

config:
discovery:
media_extractor:

history:
recorder:
  db_url: !secret maria_db_url
  purge_keep_days: 5
  exclude:
    domains:
      - calendar
    entities:
      - sensor.calendar_agenda
      - sensor.calendar_events
      - sensor.calendar_lot_thib
      - sensor.calendar_tasks

influxdb:
  host: !secret localhost
  database: home_assistant
  username: !secret influxdb_user
  password: !secret influxdb_password
  max_retries: 3
  default_measurement: state
  include:
    domains:
      - binary_sensor
      - light
      - sensor
      - person

ios:
mobile_app:
map:
person:
wake_on_lan:
sun:

google:
  client_id: !secret google_calendar_client_id
  client_secret: !secret google_calendar_client_secret

homekit:
  filter:
    include_entities:
      - switch.lsc_smart_connect_bedroom_relay
      - light.lsc_smart_connect_e27_filament_led
      - sensor.bedroom_temperature
      - sensor.living_room_temperature
      - sensor.upstairs_temperature
    include_domains:
      - scene

spotify:
  client_id: !secret spotify_id
  client_secret: !secret spotify_secret

octoprint:
  host: !secret rpi_node_fuse
  api_key: !secret octoprint_api_key
  port: 5000

binary_sensor: !include_dir_merge_list components/binary_sensors/
input_boolean: !include components/inputs/boolean.yaml
light: !include_dir_merge_list components/lights/
media_player: !include_dir_merge_list components/media_players/
notify: !include_dir_merge_list components/notifications/
panel_iframe: !include_dir_merge_named components/panel_iframes
rest_command: !include_dir_merge_named components/rest_commands
sensor: !include_dir_merge_list components/sensors/
weather: !include_dir_merge_list components/weather/

automation: !include automations.yaml
scene: !include scenes.yaml
script: !include scripts.yaml
