homeassistant:
  name: !secret home_name
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  elevation: 0
  unit_system: 'metric'
  time_zone: 'Europe/Brussels'
  customize: !include_dir_merge_named customization/

custom_updater:
  track:
    - components
    - cards
  component_urls:
    - https://raw.githubusercontent.com/thibmaek/custom-components/master/vrtnws/custom_updater.json
    - https://raw.githubusercontent.com/thibmaek/custom-components/master/telemeter/custom_updater.json
  card_urls:
    - https://raw.githubusercontent.com/kalkih/mini-media-player/master/tracker.json

lovelace:
  mode: yaml

frontend:
  javascript_version: latest
  themes: !include_dir_merge_named themes/

cloud: !include_dir_merge_named components/cloud

system_health:
logger:
  default: warn

config:
discovery:
media_extractor:
http:
  api_password: !secret http_password

mqtt:
  discovery: true
  broker: !secret localhost
  port: !secret mqtt_port
  username: !secret mqtt_user
  password: !secret mqtt_password

history:
recorder:
  db_url: !secret maria_db_url

influxdb:
  host: !secret localhost
  database: home_assistant
  username: !secret influxdb_user
  password: !secret influxdb_password
  max_retries: 3
  default_measurement: state
  include:
    domains:
      - binary_sensor
      - light
      - sensor

downloader:
  download_dir: '/share'

ios:
map:
person:
wake_on_lan:
sun:

google:
  client_id: !secret google_calendar_client_id
  client_secret: !secret google_calendar_client_secret

panel_iframe: !include_dir_merge_named components/panel_iframes/

twilio:
  account_sid: !secret twilio_account_sid
  auth_token: !secret twilio_auth_token

transmission:
  host: !secret localhost
  username: !secret transmission_user
  password: !secret transmission_pass
  turtle_mode: true

binary_sensor: !include_dir_merge_list components/binary_sensors/
camera: !include_dir_merge_list components/cameras/
device_tracker: !include_dir_merge_list components/device_trackers/
input_boolean: !include components/inputs/boolean.yaml
input_select: !include components/inputs/select.yaml
light: !include_dir_merge_list components/lights/
media_player: !include_dir_merge_list components/media_players/
notify: !include_dir_merge_list components/notifications/
plant: !include_dir_merge_named components/plants/
rest_command: !include_dir_merge_named components/rest_commands/
script: !include_dir_merge_named components/scripts/
sensor: !include_dir_merge_list components/sensors/
switch: !include_dir_merge_list components/switches/
weather: !include_dir_merge_list components/weather/

automation: !include automations.yaml
automation old: !include_dir_merge_list automations/
group: !include_dir_merge_named groups/
scene: !include_dir_merge_list scenes/
zone: !include zones.yaml
