homeassistant:
  customize: !include_dir_merge_named customization/
  packages: !include_dir_named packages/

frontend:
  javascript_version: latest
  themes: !include_dir_merge_named themes/

hacs:
  token: !secret hacs_github_token
  sidepanel_title: HACS

system_health:
logger:
  default: warn

config:
discovery:
media_extractor:

mqtt:
  discovery: true
  broker: !secret localhost
  port: !secret mqtt_port
  username: !secret mqtt_user
  password: !secret mqtt_password

history:
recorder:
  db_url: !secret maria_db_url
  exclude:
    domains:
      - calendar
    entities:
      - sensor.calendar_agenda
      - sensor.calendar_events
      - sensor.calendar_lot_thib
      - sensor.calendar_tasks

influxdb:
  host: !secret localhost
  database: home_assistant
  username: !secret influxdb_user
  password: !secret influxdb_password
  max_retries: 3
  default_measurement: state
  include:
    domains:
      - binary_sensor
      - light
      - sensor

downloader:
  download_dir: '/share'

ios:
map:
person:
wake_on_lan:
sun:

google:
  client_id: !secret google_calendar_client_id
  client_secret: !secret google_calendar_client_secret

panel_iframe: !include_dir_merge_named components/panel_iframes/

twilio:
  account_sid: !secret twilio_account_sid
  auth_token: !secret twilio_auth_token

binary_sensor: !include_dir_merge_list components/binary_sensors/
input_boolean: !include components/inputs/boolean.yaml
input_select: !include components/inputs/select.yaml
media_player: !include_dir_merge_list components/media_players/
notify: !include_dir_merge_list components/notifications/
plant: !include_dir_merge_named components/plants/
rest_command: !include_dir_merge_named components/rest_commands/
script: !include_dir_merge_named components/scripts/
sensor: !include_dir_merge_list components/sensors/
switch: !include_dir_merge_list components/switches/
weather: !include_dir_merge_list components/weather/

automation: !include automations.yaml
automation old: !include_dir_merge_list automations/
