# region: Default config
default_config:

homeassistant:
  customize: !include customize.yaml

cloud:

frontend:
  themes: !include_dir_merge_named themes/

system_health:
updater:
logger:
  default: warn

config:
discovery:
dhcp:
ssdp:
zeroconf:
mobile_app:
person:
wake_on_lan:
sun:
media_source:
image:

automation: !include automations.yaml
scene: !include scenes.yaml
script: !include scripts.yaml
# endregion

# region: History
history:
logbook:
  exclude:
    entities:
      - sensor.time
      - sensor.time_date
    entity_globs:
      - sensor.*_uptime
    domains:
      - calendar
recorder:
  db_url: !secret maria_db_url
  auto_purge: true
  purge_keep_days: 5
  exclude:
    entities:
      - sensor.time
      - sensor.time_date
    entity_globs:
      - binary_sensor.*_motion
      - sensor.octoprint_*
    domains:
      - calendar
influxdb:
  api_version: 1
  host: !secret localhost
  username: !secret influxdb_user
  password: !secret influxdb_password
  database: homeassistant
  include:
    entity_globs:
      - sensor.*_temperature
      - sensor.*_humidity
      - sensor.*_signal
      - sensor.*_uptime
      - sensor.*_current
      - sensor.*_energy
      - sensor.*_power
  exclude:
    entity_globs:
      - sensor.octoprint_*
# endregion

# region: 3rd party
tts:
  - platform: google_translate

google:
  client_id: !secret google_calendar_client_id
  client_secret: !secret google_calendar_client_secret

spotify:
  client_id: !secret spotify_id
  client_secret: !secret spotify_secret

stream:
ffmpeg:
# endregion

# region: integrations
binary_sensor: !include_dir_merge_list integrations/binary_sensors/
light: !include_dir_merge_list integrations/lights/
media_player: !include_dir_merge_list integrations/media_players/
notify: !include_dir_merge_list integrations/notifications/
rest_command: !include_dir_merge_named integrations/rest_commands
sensor: !include_dir_merge_list integrations/sensors/
switch: !include_dir_merge_list integrations/switches/
weather: !include_dir_merge_list integrations/weather/
# endregion
