# region: Default config
default_config:

homeassistant:
  customize: !include customize.yaml

cloud:

frontend:
  themes: !include_dir_merge_named themes/
  extra_module_url:
    - /hacsfiles/lovelace-card-mod/card-mod.js

logger:
  default: warn

discovery:
wake_on_lan:

automation: !include automations.yaml
scene: !include scenes.yaml
script: !include scripts.yaml
# endregion

# region: History
logbook:
  exclude: !include filters/exclude/logbook.yaml

recorder:
  db_url: !secret maria_db_url
  purge_keep_days: 5
  commit_interval: 60
  exclude: !include filters/exclude/recorder.yaml

influxdb:
  api_version: 2
  host: !secret localhost
  port: 8084
  ssl: false
  token: !secret influxdb_token
  organization: thibmaek
  bucket: homeassistant
  tags_attributes:
    - friendly_name
  include: !include filters/include/influxdb.yaml
  exclude: !include filters/exclude/influxdb.yaml
# endregion

# region: 3rd party
tts:
  - platform: google_translate

ffmpeg:

utility_meter:
  electricity:
    source: input_number.electricity_usage
  heating:
    source: input_number.heating_usage
  water:
    source: input_number.water_usage
# endregion

# region: integrations
alarm_control_panel: !include_dir_merge_list integrations/alarm_control_panel/
camera: !include_dir_merge_list integrations/cameras/
binary_sensor: !include_dir_merge_list integrations/binary_sensors/
light: !include_dir_merge_list integrations/lights/
media_player: !include_dir_merge_list integrations/media_players/
notify: !include_dir_merge_list integrations/notifications/
rest_command: !include_dir_merge_named integrations/rest_commands
sensor: !include_dir_merge_list integrations/sensors/
switch: !include_dir_merge_list integrations/switches/
weather: !include_dir_merge_list integrations/weather/
# endregion
