homeassistant:
  name: !secret home_name
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  elevation: 0
  unit_system: 'metric'
  time_zone: 'Europe/Brussels'
  customize: !include_dir_merge_named customization

frontend:
  themes: !include_dir_merge_named themes/

cloud: !include_dir_merge_named components/cloud

logger:
  default: warn

config:
discovery:
media_extractor:
updater:
history:
logbook:
recorder:
http:
  api_password: !secret http_password

mqtt:
  discovery: true
  broker: !secret mqtt_broker
  port: !secret mqtt_port
  username: !secret mqtt_user
  password: !secret mqtt_password

influxdb:
  host: localhost
  database: homeassistant
  username: !secret influxdb_user
  password: !secret influxdb_password
  max_retries: 3
  default_measurement: state
  include:
    domains:
      - sensor

downloader:
  download_dir: '/share'

ios:
map:

wake_on_lan:

conversation:
tts:
  platform: 'google'

google:
  client_id: !secret google_calendar_client_id
  client_secret: !secret google_calendar_client_secret

sun:

weblink:
  entities: !include_dir_merge_list components/weblinks/

panel_iframe: !include_dir_merge_named components/panel_iframes/

twilio:
  account_sid: !secret twilio_account_sid
  auth_token: !secret twilio_auth_token

binary_sensor: !include_dir_merge_list components/binary_sensors/
camera: !include_dir_merge_list components/cameras/
device_tracker: !include_dir_merge_list components/device_trackers/
input_boolean: !include components/inputs/boolean.yaml
input_select: !include components/inputs/select.yaml
light: !include_dir_merge_list components/lights/
media_player: !include_dir_merge_list components/media_players/
notify: !include_dir_merge_list components/notifications/
plant: !include_dir_merge_named components/plants/
script: !include_dir_merge_named components/scripts/
sensor: !include_dir_merge_list components/sensors/
switch: !include_dir_merge_list components/switches/
weather: !include_dir_merge_list components/weather/

automation: !include automations.yaml
automation old: !include_dir_merge_list automations_old/
group: !include_dir_merge_named groups/
scene: !include_dir_merge_list scenes/
zone: !include zones.yaml
