resources:
  - url: https://unpkg.com/moment@2.22.2/moment.js
    type: js
  - url: /local/custom-ui/calendar-card/calendar-card.js?v=1.0.1
    type: module
  - url: /local/tracker-card.js?v=0
    type: js
  - url: /local/mini-media-player-bundle.js?v=0.9.8
    type: module
  - url: /local/custom-lovelace/entity-attributes-card/entity-attributes-card.js?v=1
    type: js
  - url: /local/custom-lovelace/circle-sensor-card/circle-sensor-card.js?v=1
    type: module

title: 'Home'
views:
  - title: 'Maekelberghain'
    icon: "mdi:home"
    cards: !include lovelace/views/home.yaml

  - title: 'Beneden'
    icon: "mdi:sofa"
    cards: !include lovelace/views/livingroom.yaml

  - title: 'Slaapkamer'
    icon: "mdi:bed-empty"
    cards: !include lovelace/views/bedroom.yaml

  - title: "Work (In The Pocket)"
    icon: "mdi:briefcase"
    cards: !include lovelace/views/work.yaml

  - title: 'Weather'
    icon: "mdi:weather-fog"
    cards: !include lovelace/views/weather.yaml

  - title: 'Server'
    icon: "mdi:server"
    path: 'server'
    cards: !include lovelace/views/server.yaml

  - title: "Home Assistant Internals"
    icon: "mdi:home-automation"
    path: 'internals'
    cards: !include lovelace/views/ha_internals.yaml

  - title: "Misc."
    cards: !include lovelace/views/misc.yaml
