resources:
  - url: https://unpkg.com/moment@2.22.2/moment.js
    type: js
  - url: /local/custom-ui/calendar-card/calendar-card.js?v=1.0.1
    type: module
  - url: /local/custom-ui/animated-weather-card/animated-weather-card.js?v=6
    type: js

title: Home
views:
  - title: Maekelberghain
    icon: mdi:home
    cards:
      - type: horizontal-stack
        cards:
          - type: entities
            entities:
              - sensor.date
          - type: entities
            entities:
              - sensor.time
      - type: "custom:calendar-card"
        name: 'Calendar'
        entities:
          - calendar.lot__thib
          - calendar.taken
      - type: map
        default_zoom: 13.5
        entities:
          - device_tracker.thibaults_iphone
      - type: entity-filter
        entities:
          - device_tracker.thibaults_iphone
        state_filter:
          - 'home'
        show_empty: false
        show_state: false
        card:
          title: "Who's Home"
          type: glance
      - type: entity-filter
        entities:
          - light.tradfri_bulb_e27_opal_1000lm
          - light.tradfri_bulb_e27_cws_opal_600lm
        state_filter:
          - "on"
        show_empty: false
        show_header_toggle: true
        card:
          title: "Enabled lights"
          type: glance
      - type: entities
        entities:
          - binary_sensor.garage_motion
          - input_boolean.vacation_mode
          - sensor.telenet_off_peak
      - type: picture-entity
        title: Buienradar Radarmap
        entity: camera.buienradar_radarmap
        camera_image: camera.buienradar_radarmap
        show_info: true
        tap_action: dialog
      - type: picture-entity
        title: Garage camera
        entity: camera.garage_camera
        camera_image: camera.garage_camera
        show_info: true
        tap_action: dialog
      - type: entities
        title: Tomorrow's Weather
        show_header_toggle: true
        entities:
          - sensor.dark_sky_weather_cloud_coverage_1
          - sensor.dark_sky_weather_daily_max_precip_intensity_1
          - sensor.dark_sky_weather_precip_1
          - sensor.dark_sky_weather_precip_intensity_1
          - sensor.dark_sky_weather_precip_probability_1
          - sensor.dark_sky_weather_wind_speed
      - type: entities
        title: "Today's schedule"
        entities:
          - sensor.day_of_week
          - sensor.calendar_agenda
          - sensor.calendar_events
          - sensor.calendar_facebook
          - sensor.calendar_lotte__thib
          - sensor.calendar_tasks
      - type: entities
        title: HP Printer ink levels
        show_header_toggle: true
        entities:
          - sensor.printer_ink_level_cyan
          - sensor.printer_ink_level_magenta
          - sensor.printer_ink_level_yellow
          - sensor.printer_ink_level_black
      - type: glance
        title: "Radio Stations"
        show_header_toggle: true
        entities:
          - entity: sensor.bbc_radio_1_live
          - entity: sensor.worldwide_fm_live
      - type: entities
        title: Vandaag
        show_header_toggle: true
        entities:
          - sensor.dark_sky_weather_apparent_temperature
          - sensor.dark_sky_weather_daily_summary
          - sensor.dark_sky_weather_precip_probability
          - sensor.flights_home
          - sensor.moon
          - sensor.season_template
          - sensor.waze_work_travel_time
          - sun.sun
      - type: glance
        title: Waste collection
        columns: 3
        show_state: false
        entities:
          - entity: binary_sensor.waste_collection_carboard
            name: Cardboard
          - entity: binary_sensor.waste_collection_pmd
            name: PMD
          - entity: binary_sensor.waste_collection_trash
            name: Trash
      - type: media-control
        entity: media_player.spotify
      - type: weather-forecast
        entity: weather.weather_brugge
      - type: custom:animated-weather-card
        entity_sun: sun.sun
        entity_daily_summary: sensor.dark_sky_weather_daily_summary
        entity_current_conditions: sensor.dark_sky_weather_icon
        entity_humidity: sensor.dark_sky_weather_humidity
        entity_pressure: sensor.dark_sky_weather_pressure
        entity_temperature: sensor.dark_sky_weather_temperature
        entity_visibility: sensor.dark_sky_weather_visibility
        entity_wind_bearing: sensor.dark_sky_weather_wind_bearing
        entity_wind_speed: sensor.dark_sky_weather_wind_speed
        entity_forecast_high_temp_1: sensor.dark_sky_weather_daytime_high_temperature_1
        entity_forecast_high_temp_2: sensor.dark_sky_weather_daytime_high_temperature_2
        entity_forecast_high_temp_3: sensor.dark_sky_weather_daytime_high_temperature_3
        entity_forecast_high_temp_4: sensor.dark_sky_weather_daytime_high_temperature_4
        entity_forecast_high_temp_5: sensor.dark_sky_weather_daytime_high_temperature_5
        entity_forecast_low_temp_1: sensor.dark_sky_weather_overnight_low_temperature
        entity_forecast_low_temp_2: sensor.dark_sky_weather_overnight_low_temperature_1
        entity_forecast_low_temp_3: sensor.dark_sky_weather_overnight_low_temperature_2
        entity_forecast_low_temp_4: sensor.dark_sky_weather_overnight_low_temperature_3
        entity_forecast_low_temp_5: sensor.dark_sky_weather_overnight_low_temperature_4
        entity_forecast_icon_1: sensor.dark_sky_weather_icon_1
        entity_forecast_icon_2: sensor.dark_sky_weather_icon_2
        entity_forecast_icon_3: sensor.dark_sky_weather_icon_3
        entity_forecast_icon_4: sensor.dark_sky_weather_icon_4
        entity_forecast_icon_5: sensor.dark_sky_weather_icon_5

  - title: Work (In The Pocket)
    icon: mdi:briefcase
    cards:
      - type: entities
        title: Work (In The Pocket)
        show_header_toggle: true
        entities:
          - binary_sensor.workday_sensor
          - input_boolean.out_of_office
          - binary_sensor.water_work_plants
          - sensor.flights_work
          - sensor.waze_home_travel_time
      - type: weather-forecast
        entity: weather.weather_gent

  - title: Beneden
    icon: mdi:sofa
    cards:
      - type: entities
        entities:
          - light.living_room_lights
          - scene.goodnight
          - scene.having_dinner
          - scene.watching_a_movie
          - switch.turn_on_tv
      - type: entities
        title: Living Room Lights
        show_header_toggle: true
        entities:
          - entity: switch.tradfri_control_outlet_3
            icon: mdi:pine-tree
          - light.tradfri_bulb_e27_opal_1000lm
          - sensor.tradfri_wireless_dimmer
      - type: entities
        title: Spotify
        show_header_toggle: true
        entities:
          - input_select.spotify_playlist
          - input_select.spotify_source
          - script.spotify_music
      - type: media-control
        entity: media_player.panasonic_viera
      - type: media-control
        entity: media_player.playstation_4
      - type: media-control
        entity: media_player.volumio_woonkamer
      - type: media-control
        entity: media_player.woonkamer_chromecast
      - type: plant-status
        entity: plant.ficus_elastica

  - title: Slaapkamer
    icon: mdi:bed-empty
    cards:
      - type: entities
        entities:
          - light.bedroom_lights
          - scene.late_night_working
          - scene.sexy_mode
          - scene.working_at_my_desk
          - sensor.discogs_random_record
      - type: picture-entity
        title: Bedroom camera
        entity: camera.bedroom_camera
        camera_image: camera.bedroom_camera
        show_info: true
        tap_action: dialog
      - type: entities
        title: Bedroom Lights
        show_header_toggle: true
        entities:
          - entity: switch.bed_lights
            icon: mdi:lightbulb
          - entity: switch.stringlights
            icon: mdi:lightbulb
          - light.tradfri_bulb_e27_cws_opal_600lm
          - sensor.tradfri_remote_control
          - sensor.switch_bedlights
          - sensor.switch_stringlights
          - switch.flux
      - type: entities
        title: Media
        show_header_toggle: true
        entities:
          - sensor.discogs
          - sensor.panorama_plex
      - type: horizontal-stack
        cards:
          - type: sensor
            entity: sensor.bedroom_humidity
            name: Humidity
            height: 100
            line_color: "#1e8cd7"
          - type: sensor
            entity: sensor.bedroom_temperature
            name: Temperature
            height: 40
            line_color: "#1e8cd7"
      - type: plant-status
        entity: plant.monstera_deliciosa

  - title: Server
    icon: mdi:raspberrypi
    cards:
      - type: horizontal-stack
        title: Network
        cards:
          - type: sensor
            entity: sensor.speedtest_ping
            icon: mdi:resistor
            name: Ping
          - type: sensor
            entity: sensor.speedtest_download
            icon: mdi:download
            name: Download
          - type: sensor
            entity: sensor.speedtest_upload
            icon: mdi:upload
            name: Upload
      - type: horizontal-stack
        cards:
          - type: sensor
            title: "CPU usage"
            entity: sensor.processor_use
          - type: sensor
            title: "MEM usage"
            entity: sensor.memory_use
          - type: sensor
            title: "HDD usage"
            entity: sensor.disk_use_
      - type: entities
        title: Cryptocurrency
        entities:
          - sensor.eth_balance
          - sensor.exchange_rate_1_btc
          - sensor.trade_volume
      - type: entities
        title: Server Internals
        show_header_toggle: true
        entities:
          - sensor.current_version
          - sensor.disk_free_
          - sensor.memory_free
          - sensor.myip
          - sensor.uptime
          - updater.updater
      - type: glance
        title: Network Hosts
        show_header_toggle: true
        columns: 3
        show_state: false
        entities:
          - binary_sensor.panorama_host
          - binary_sensor.tresor_host
          - binary_sensor.nextcloudpi_host
          - binary_sensor.rasplex_host
          - binary_sensor.ps4_host
          - binary_sensor.volumio_woonkamer_host
      - type: entities
        title: Weblinks
        show_header_toggle: true
        entities:
          - type: weblink
            name: "States (deprecated)"
            url: "/states"
            icon: 'mdi:home-assistant'
          - type: weblink
            name: "Home Assistant Components"
            url: "https://home-assistant.io/components/"
            icon: 'mdi:home-assistant'
          - type: weblink
            name: 'Speedtest'
            url: "https://beta.speedtest.net"
            icon: 'mdi:speedometer'
          - type: weblink
            name: "Mijn Telenet"
            url: "https://mijn.telenet.be/mijntelenet/homenetwork/overview.do"
            icon: mdi:access-point-network
          - weblink.nextcloud
          - weblink.panorama_plex
          - weblink.sickrage
          - weblink.transmission
      - type: entities
        title: Network
        entities:
          - name: "Received bytes"
            secondary_info: last-changed
            entity: sensor.compal_broadband_networks_inc_ch6643_bytes_received
          - name: "Sent bytes"
            secondary_info: last-changed
            entity: sensor.compal_broadband_networks_inc_ch6643_bytes_sent
          - name: "Received bytes (kb/sec)"
            secondary_info: last-changed
            entity: sensor.compal_broadband_networks_inc_ch6643_kbytesec_received
          - name: "Sent bytes (kb/sec)"
            secondary_info: last-changed
            entity: sensor.compal_broadband_networks_inc_ch6643_kbytesec_sent
          - type: divider
            style:
          - name: "Received packets"
            secondary_info: last-changed
            entity: sensor.compal_broadband_networks_inc_ch6643_packets_received
          - name: "Sent packets"
            secondary_info: last-changed
            entity: sensor.compal_broadband_networks_inc_ch6643_packets_sent
          - name: "Received packets (pck/sec)"
            secondary_info: last-changed
            entity: sensor.compal_broadband_networks_inc_ch6643_packetssec_received
          - name: "Sent packets (pck/sec)"
            secondary_info: last-changed
            entity: sensor.compal_broadband_networks_inc_ch6643_packetssec_sent

  - title: Home Assistant Internals
    icon: mdi:home-automation
    cards:
      - type: entities
        title: Server Actions
        show_header_toggle: true
        entities:
          - script.ha_check_config
          - script.ha_reload_automations
          - script.ha_reload_core
          - script.ha_reload_groups
          - script.ha_reload_scripts
      - type: entities
        title: 'Automations'
        show_header_toggle: true
        entities:
          - entity: group.all_automations
            name: All Automations
            icon: mdi:arrow-decision-auto
          - automation.alert_if_tradfri_remotes_go_below_10
          - automation.backup_snapshots_to_google_drive
          - automation.notify_if_someone_is_in_the_garage
          - automation.notify_if_the_plants_at_work_need_to_be_watered
          - automation.notify_if_there_is_rain_coming
