resources:
  - url: https://unpkg.com/moment@2.22.2/moment.js
    type: js
  - url: /local/custom-ui/calendar-card/calendar-card.js?v=1.0.1
    type: module
  - url: /local/tracker-card.js?v=0
    type: js
  - url: /local/custom-lovelace/compact-custom-header/compact-custom-header.js
    type: js
  - url: /local/mini-media-player-bundle.js?v=0.9.8
    type: module
  - url: /local/custom-lovelace/entity-attributes-card/entity-attributes-card.js?v=1
    type: js
  - url: /local/custom-lovelace/circle-sensor-card/circle-sensor-card.js?v=1
    type: module

title: Home
views: !include_dir_merge_list lovelace/views/
