- platform: samsungtv_custom
  protocol: ws
  port: 8002
  host: !secret samsung_ru7100_host
  mac: !secret samsung_ru7100_mac
  sourcelist: '{"Telenet TV": "KEY_HDMI1", "Playstation 4": "KEY_HDMI2", "Chromecast": "KEY_HDMI3"}'
  applist: "YouTube, Plex, Spotify"
