substitutions:
  device_name: esp32-macropad
  friendly_name: "ESP32 Macropad"

packages:
  base_config: !include ../../common/base.yaml
  wifi: !include ../../common/wifi.yaml
  i2c: !include ../../common/i2c.yaml
  mqtt: !include ../../common/mqtt.yaml
  integrated: !include ../../common/integrated.yaml
  metrics: !include ../../common/metrics.yaml

esphome:
  platform: ESP32
  board: nodemcu-32s

api:
  services:
    - service: set_last_action
      variables:
        action: string
      then:
        - lambda: |-
            id(last_action).publish_state(action);
        - display.page.show: action_page
        - delay: 10s
        - display.page.show: time_page
    - service: show_prev_page
      then:
        - display.page.show_previous: oled_display
    - service: show_next_page
      then:
        - display.page.show_next: oled_display
    - service: show_initial_page
      then:
        - display.page.show: time_page

script:
  - id: reset_mode
    then:
      - select.set:
          id: mode_select
          option: "Lights"
  - id: next_mode
    then:
      - select.set:
          id: mode_select
          option: !lambda |-
            if (id(mode_select).state == "Lights") {
              return "Media";
            }
            if (id(mode_select).state == "Media") {
              return "Lights";
            }
            return "";

time:
  - platform: homeassistant
    id: esptime

select:
  - platform: template
    entity_category: config
    id: mode_select
    name: "Mode"
    optimistic: true
    initial_option: "Lights"
    options:
      - "Lights"
      - "Media"

binary_sensor:
  - platform: gpio
    name: "${friendly_name} — Mode Button"
    internal: true
    pin:
      number: GPIO23
      mode: INPUT_PULLUP
      inverted: true
    on_click:
      min_length: 1s
      max_length: 2s
      then:
        - script.execute: reset_mode
    on_press:
      - script.execute: next_mode

  - platform: gpio
    name: "${friendly_name} — Button 1"
    internal: true
    pin:
      number: GPIO19
      mode: INPUT_PULLUP
      inverted: true
    on_press:
      - mqtt.publish:
          topic: "esphome/${device_name}/button"
          payload: "1"
    on_click:
      min_length: 1s
      max_length: 2s
      then:
        - mqtt.publish:
            topic: "esphome/${device_name}/button_hold"
            payload: "1"
  - platform: gpio
    name: "${friendly_name} — Button 2"
    internal: true
    pin:
      number: GPIO18
      mode: INPUT_PULLUP
      inverted: true
    on_press:
      - mqtt.publish:
          topic: "esphome/${device_name}/button"
          payload: "2"
    on_click:
      min_length: 1s
      max_length: 2s
      then:
        - mqtt.publish:
            topic: "esphome/${device_name}/button_hold"
            payload: "2"
  - platform: gpio
    name: "${friendly_name} — Button 3"
    internal: true
    pin:
      number: GPIO5
      mode: INPUT_PULLUP
      inverted: true
    on_press:
      - mqtt.publish:
          topic: "esphome/${device_name}/button"
          payload: "3"
    on_click:
      min_length: 1s
      max_length: 2s
      then:
        - mqtt.publish:
            topic: "esphome/${device_name}/button_hold"
            payload: "3"
  - platform: gpio
    name: "${friendly_name} — Button 4"
    internal: true
    pin:
      number: GPIO17
      mode: INPUT_PULLUP
      inverted: true
    on_press:
      - mqtt.publish:
          topic: "esphome/${device_name}/button"
          payload: "4"
    on_click:
      min_length: 1s
      max_length: 2s
      then:
        - mqtt.publish:
            topic: "esphome/${device_name}/button_hold"
            payload: "4"
  - platform: gpio
    name: "${friendly_name} — Button 5"
    internal: true
    pin:
      number: GPIO16
      mode: INPUT_PULLUP
      inverted: true
    on_press:
      - mqtt.publish:
          topic: "esphome/${device_name}/button"
          payload: "5"
    on_click:
      min_length: 1s
      max_length: 2s
      then:
        - mqtt.publish:
            topic: "esphome/${device_name}/button_hold"
            payload: "5"
  - platform: gpio
    name: "${friendly_name} — Button 6"
    internal: true
    pin:
      number: GPIO12
      mode: INPUT_PULLUP
      inverted: true
    on_press:
      - mqtt.publish:
          topic: "esphome/${device_name}/button"
          payload: "6"
    on_click:
      min_length: 1s
      max_length: 2s
      then:
        - mqtt.publish:
            topic: "esphome/${device_name}/button_hold"
            payload: "6"
  - platform: gpio
    name: "${friendly_name} — Button 7"
    internal: true
    pin:
      number: GPIO14
      mode: INPUT_PULLUP
      inverted: true
    on_press:
      - mqtt.publish:
          topic: "esphome/${device_name}/button"
          payload: "7"
    on_click:
      min_length: 1s
      max_length: 2s
      then:
        - mqtt.publish:
            topic: "esphome/${device_name}/button_hold"
            payload: "7"
  - platform: gpio
    name: "${friendly_name} — Button 8"
    internal: true
    pin:
      number: GPIO27
      mode: INPUT_PULLUP
      inverted: true
    on_press:
      - mqtt.publish:
          topic: "esphome/${device_name}/button"
          payload: "8"
    on_click:
      min_length: 1s
      max_length: 2s
      then:
        - mqtt.publish:
            topic: "esphome/${device_name}/button_hold"
            payload: "8"
  - platform: gpio
    name: "${friendly_name} — Button 9"
    internal: true
    pin:
      number: GPIO15
      mode: INPUT_PULLUP
      inverted: true
    on_press:
      - mqtt.publish:
          topic: "esphome/${device_name}/button"
          payload: "9"
    on_click:
      min_length: 1s
      max_length: 2s
      then:
        - mqtt.publish:
            topic: "esphome/${device_name}/button_hold"
            payload: "9"
  - platform: gpio
    name: "${friendly_name} — Button 10"
    internal: true
    pin:
      number: GPIO4
      mode: INPUT_PULLUP
      inverted: true
    on_press:
      - mqtt.publish:
          topic: "esphome/${device_name}/button"
          payload: "10"
    on_click:
      min_length: 1s
      max_length: 2s
      then:
        - mqtt.publish:
            topic: "esphome/${device_name}/button_hold"
            payload: "10"

text_sensor:
  - platform: template
    id: last_action
    name: "${friendly_name} — Last action"
    entity_category: diagnostic
    icon: mdi:application-cog-outline

font:
  - file: '../../assets/fonts/din_alt.ttf'
    id: din_sm
    size: 11
  - file: '../../assets/fonts/din_alt.ttf'
    id: din
    size: 16
  - file: '../../assets/fonts/mdi.ttf'
    id: mdi
    size: 12
    glyphs:
      - "\U000F0335" # mdi-lightbulb
      - "\U000F0386" # mdi-music-circle

display:
  - platform: ssd1306_i2c
    id: oled_display
    model: "SH1106 128x32"
    address: 0x3C
    contrast: 100%
    pages:
      - id: time_page
        lambda: |-
          it.line(0, 15, it.get_width(), 15);
          auto time = id(esptime).now();
          if (time.is_valid()) {
            it.strftime(2, it.get_height(), id(din), TextAlign::BOTTOM_LEFT, "%H:%M", time);
          }

          if (id(mode_select).has_state()) {
            it.printf(1, 2, id(din_sm), TextAlign::TOP_LEFT, "Mode: %s", id(mode_select).state.c_str());
            if (id(mode_select).state == "Lights") {
              it.printf(it.get_width() - 4, 2, id(mdi), TextAlign::TOP_RIGHT, "\U000F0335");
            } else if (id(mode_select).state == "Media") {
              it.printf(it.get_width() - 4, 2, id(mdi), TextAlign::TOP_RIGHT, "\U000F0386");
            }
          }
      - id: action_page
        lambda: |-
          it.line(0, 15, it.get_width(), 15);

          if (id(mode_select).has_state()) {
            it.printf(1, 2, id(din_sm), TextAlign::TOP_LEFT, "Mode: %s", id(mode_select).state.c_str());
            it.printf(2, it.get_height(), id(din), TextAlign::BOTTOM_LEFT, "%s", id(last_action).state.c_str());
            if (id(mode_select).state == "Lights") {
              it.printf(it.get_width() - 4, 2, id(mdi), TextAlign::TOP_RIGHT, "\U000F0335");
            } else if (id(mode_select).state == "Media") {
              it.printf(it.get_width() - 4, 2, id(mdi), TextAlign::TOP_RIGHT, "\U000F0386");
            }
          } else {
            it.print(it.get_width() / 2, it.get_height() / 2, id(din), TextAlign::CENTER, "...");
          }
