- platform: switch
  name: "Betonlamp"
  entity_id: switch.betonlamp

- platform: switch
  name: "Lampje Stellingkast"
  entity_id: switch.silvercrest_plug

- platform: switch
  name: "Kastlampje"
  entity_id: switch.kastlampje

- platform: switch
  name: "Lampje Togo"
  entity_id: switch.tradfri_outlet_togo_switch

- platform: switch
  name: "Badkamer Lampje Thib"
  entity_id: switch.shelly_25_badkamer_channel_1

- platform: switch
  name: "Badkamer Lampje Lotte"
  entity_id: switch.shelly_25_badkamer_channel_2
