- platform: switch
  name: Betonlamp
  entity_id: switch.betonlamp

- platform: switch
  name: Lampje Togo
  entity_id: switch.lsc_smart_connect_switch_leeshoekje

- platform: switch
  name: Lampje zitzak
  entity_id: switch.lsc_smart_connect_switch_upstairs

- platform: switch
  name: Badkamer Lampje Thib
  entity_id: switch.shelly_25_badkamer_channel_1

- platform: switch
  name: Badkamer Lampje Lotte
  entity_id: switch.shelly_25_badkamer_channel_2
