clearhistory:
  description: "Clear your history."
clearlogs:
  description: "Clear your logs."
forcedailysearch:
  description: "Force a daily search."
forcepropersearch:
  description: "Force a proper search."
restart:
  description: "Restart service."
shutdown:
  description: "Shutdown service"
update:
  description: "Check for update."
