- platform: template
  sensors:
    octoprint_preheating:
      friendly_name: "Octoprint Preheating"
      entity_id:
        - binary_sensor.octoprint_printing
        - sensor.octoprint_current_state
        - sensor.octoprint_target_tool0_temp
        - sensor.octoprint_target_bed_temp
        - sensor.octoprint_actual_tool0_temp
        - sensor.octoprint_actual_bed_temp
      device_class: heat
      value_template: >-
        {{
          is_state('sensor.octoprint_current_state', 'Operational')
          and is_state('binary_sensor.octoprint_printing', 'off')
          and states('sensor.octoprint_actual_tool0_temp')|int >= states('sensor.octoprint_target_tool0_temp')|int
          and states('octoprint_actual_bed_temp')|int >= states('octoprint_target_bed_temp')|int
        }}

- platform: template
  sensors:
    updater_supervisor:
      friendly_name: "Updater (Supervisor)"
      device_class: problem
      entity_id: sensor.supervisor_updates
      value_template: >
        {{ state_attr('sensor.supervisor_updates', 'current_version') != state_attr('sensor.supervisor_updates', 'newest_version') }}
      availability_template: >
        {{ (states('sensor.supervisor_updates') | int(-1)) > -1 }}
    updater_hacs:
      friendly_name: "Updater (HACS)"
      device_class: problem
      entity_id: sensor.hacs
      value_template: >
        {{ states('sensor.hacs') | int > 0 }}
    updater_addons:
      friendly_name: "Updater (Addons)"
      device_class: problem
      entity_id: sensor.supervisor_updates
      value_template: >
        {{ states('sensor.supervisor_updates') | int > 0 }}

- platform: template
  sensors:
    no_one_home:
      friendly_name: "No one home"
      value_template: >
        {{
          not is_state("person.thibault", "home")
          and not is_state("person.lotte", "home")
        }}
