- platform: template
  sensors:
    no_one_home:
      friendly_name: "No one home"
      icon_template: >
        {% if is_state("binary_sensor.no_one_home", "on") %}
          mdi:account-multiple-remove
        {% else %}
          mdi:account-multiple-check
        {% endif %}
      value_template: >
        {{
          not is_state("person.thibault", "home")
          and not is_state("person.lotte", "home")
        }}

- platform: template
  sensors:
    house_activity:
      friendly_name: "House activity"
      icon_template: >
        {% if is_state("binary_sensor.house_activity", "on") %}
          mdi:motion-sensor
        {% else %}
          mdi:motion-sensor-off
        {% endif %}
      value_template: >
        {{
          is_state("binary_sensor.bathroom_motion_occupancy", "on")
          or is_state("binary_sensor.bedroom_motion_occupancy", "on")
          or is_state("binary_sensor.bureau_motion_occupancy", "on")
          or is_state("binary_sensor.keuken_motion_occupancy", "on")
          or is_state("binary_sensor.leeshoekje_motion_occupancy", "on")
          or is_state("binary_sensor.livingroom_motion_occupancy", "on")
          or is_state("binary_sensor.studio_motion_occupancy", "on")
        }}

# Dark rooms
- platform: template
  sensors:
    bedroom_dark:
      friendly_name: "Bedroom dark"
      icon_template: >
        {% if is_state("binary_sensor.bedroom_dark", "on") %}
          mdi:brightness-2
        {% else %}
          mdi:brightness-7
        {% endif %}
      value_template: >
        {{ states('sensor.light_intensity_bedroom_illuminance_lux') | int < 70 }}
    living_dark:
      friendly_name: "Living dark"
      icon_template: >
        {% if is_state("binary_sensor.living_dark", "on") %}
          mdi:brightness-2
        {% else %}
          mdi:brightness-7
        {% endif %}
      value_template: >
        {{ states('sensor.light_intensity_living_illuminance_lux') | int < 70 }}
    kitchen_dark:
      friendly_name: "Kitchen dark"
      icon_template: >
        {% if is_state("binary_sensor.kitchen_dark", "on") %}
          mdi:brightness-2
        {% else %}
          mdi:brightness-7
        {% endif %}
      value_template: >
        {{ states('sensor.kitchen_illuminance') | int < 70 }}

# Fully Kiosk
- platform: template
  sensors:
    fully_screen_state:
      friendly_name: "Fully Kiosk Screen State"
      value_template: >-
        {% if is_state('sensor.fully_kiosk_event', 'screenOn') %}
          true
        {% elif is_state('sensor.fully_kiosk_event', 'screenOff') %}
          false
        {% endif %}
      icon_template: >
        {% if is_state('sensor.fully_kiosk_event', 'screenOn') %}
          mdi:card-outline
        {% elif is_state('sensor.fully_kiosk_event', 'screenOff') %}
          mdi:card-off-outline
        {% endif %}
      device_class: power
    fully_motion:
      friendly_name: "Fully Kiosk Motion"
      value_template: >
        {{ is_state('sensor.fully_kiosk_event', 'onMotion') }}
      device_class: motion
