- platform: template
  sensors:
    updater_supervisor:
      unique_id: updater_supervisor
      friendly_name: "Updater (Supervisor)"
      device_class: problem
      icon_template: mdi:home-assistant
      entity_id: sensor.supervisor_updates
      value_template: >
        {{ state_attr('sensor.supervisor_updates', 'current_version') != state_attr('sensor.supervisor_updates', 'newest_version') }}
      availability_template: >
        {{ (states('sensor.supervisor_updates') | int(-1)) > -1 }}
    updater_hacs:
      unique_id: updater_hacs
      friendly_name: "Updater (HACS)"
      device_class: problem
      icon_template: mdi:store
      entity_id: sensor.hacs
      value_template: >
        {{ states('sensor.hacs') | int > 0 }}
    updater_addons:
      unique_id: updater_addons
      friendly_name: "Updater (Addons)"
      device_class: problem
      icon_template: mdi:puzzle
      entity_id: sensor.supervisor_updates
      value_template: >
        {{ states('sensor.supervisor_updates') | int > 0 }}

- platform: template
  sensors:
    no_one_home:
      friendly_name: "No one home"
      value_template: >
        {{
          not is_state("person.thibault", "home")
          and not is_state("person.lotte", "home")
        }}
