- platform: template
  sensors:
    no_one_home:
      friendly_name: "No one home"
      value_template: >
        {{
          not is_state("person.thibault", "home")
          and not is_state("person.lotte", "home")
        }}

# Dark rooms
- platform: template
  sensors:
    bedroom_dark:
      friendly_name: "Bedroom dark"
      value_template: >
        {{ states('sensor.light_intensity_bedroom_illuminance_lux') | int < 70 }}
    living_dark:
      friendly_name: "Living dark"
      value_template: >
        {{ states('sensor. !env_var ') | int < 70 }}
    kitchen_dark:
      friendly_name: "Kitchen dark"
      value_template: >
        {{ states('sensor.kitchen_illuminance') | int < 70 }}
