- platform: tod
  name: Morning
  after: "08:00"
  before: "12:00"

- platform: tod
  name: 'Noon'
  after: "12:00"
  before: "18:00"

- platform: tod
  name: "Evening"
  after: "18:00"
  before: "22:00"

- platform: tod
  name: 'Night'
  after: "22:00"
  before: "08:00"

# region: Working Day
- platform: tod
  name: "Office Hours (Morning)"
  after: "10:00"
  before: "12:00"
- platform: tod
  name: "Lunch Break"
  after: "12:00"
  before: "13:00"
- platform: tod
  name: "Office Hours (Afternoon)"
  after: "13:00"
  before: "18:00"
# endregion
