substitutions:
  device_name: esp8266-bedroom-controller-thib
  friendly_name: "Bedroom Controller Thib"

packages:
  base_config: !include ../../common/base.yaml
  wifi: !include ../../common/wifi.yaml
  integrated: !include ../../common/integrated.yaml

esphome:
  platform: ESP8266
  board: d1_mini

binary_sensor:
  - platform: gpio
    id: button_brown
    name: "${friendly_name} - Button Right"
    icon: mdi:arrow-right-drop-circle
    pin: D6
    filters:
      - delayed_on: 20ms
    on_press:
      - light.turn_off: leds
      - light.turn_on:
          id: leds
          brightness: 80%
          red: 100%
          green: 85%
          blue: 43%
      - delay: 1s
      - light.turn_off: leds
  - platform: gpio
    id: button_yellow
    name: "${friendly_name} - Button Center"
    icon: mdi:arrow-down-drop-circle
    pin: D7
    filters:
      - delayed_on: 20ms
    on_press:
      - light.turn_off: leds
      - light.turn_on:
          id: leds
          brightness: 80%
          red: 87%
          green: 100%
          blue: 75%
      - delay: 1s
      - light.turn_off: leds
  - platform: gpio
    id: button_orange
    name: "${friendly_name} - Button Left"
    icon: mdi:arrow-left-drop-circle
    pin: D8
    filters:
      - delayed_on: 20ms
    on_press:
      - light.turn_off: leds
      - light.turn_on:
          id: leds
          brightness: 80%
          red: 100%
          green: 64%
          blue: 28%
      - delay: 1s
      - light.turn_off: leds

light:
  - platform: fastled_clockless
    id: leds
    pin: D4
    chipset: WS2812B
    num_leds: 4
    rgb_order: GRB
    effects:
      - automation:
          name: Breathe
          sequence:
            - delay: 1s
            - light.dim_relative:
                id: leds
                relative_brightness: 50%
                transition_length: 4s
            - delay: 1s
            - light.dim_relative:
                id: leds
                relative_brightness: -50%
                transition_length: 4s
