substitutions:
  device_name: esp8266-kitchen-air-quality
  friendly_name: "Kitchen Air Quality"

esphome:
  platform: ESP8266
  board: d1_mini

packages:
  base: !include ../../common/base.yaml
  wifi: !include ../../common/wifi.yaml
  integrated: !include ../../common/integrated.yaml
  metrics: !include ../../common/metrics.yaml

uart:
  rx_pin: D2
  baud_rate: 9600

globals:
  - id: warn_threshold
    type: int
    initial_value: '35'
  - id: danger_treshold
    type: int
    initial_value: '55'

binary_sensor:
  # Ref: https://blissair.com/what-is-pm-2-5.htm
  - platform: template
    name: "${friendly_name} Safety"
    device_class: safety
    lambda: |-
      if (id(pm2_5_sensor).state < id(danger_treshold)) {
        return false;
      } else {
        return true;
      }

sensor:
  - platform: pm1006
    pm_2_5:
      name: "${friendly_name}"
      id: pm2_5_sensor

text_sensor:
  - platform: template
    name: "${friendly_name} — State"
    icon: mdi:air-filter
    lambda: |-
      if (id(pm2_5_sensor).state < id(warn_threshold)) {
        return {"safe"};
      } else if(id(pm2_5_sensor).state < id(danger_treshold)) {
        return {"risky"};
      } else {
        return {"dangerous"};
      }
