substitutions:
  device_name: esp8266-led-dimmer
  friendly_name: "ESP8266 LED Dimmer"

esphome:
  platform: ESP8266
  board: d1_mini

packages:
  base_config: !include ../../common/base.yaml
  wifi: !include ../../common/wifi.yaml
  integrated: !include ../../common/integrated.yaml

output:
  - platform: esp8266_pwm
    pin: GPIO12
    id: mosfet_pwm

light:
  - platform: monochromatic
    output: mosfet_pwm
    name: "LED Strips"
