substitutions:
  device_name: esp8266-node-kitchen
  friendly_name: "ESP8266 Node Kitchen"
  room: "Kitchen"

esphome:
  platform: ESP8266
  board: d1_mini

packages:
  base_config: !include ../../common/base.yaml
  wifi: !include ../../common/wifi.yaml
  integrated: !include ../../common/integrated.yaml
  i2c: !include ../../common/i2c.yaml

# binary_sensor:
#   - platform: gpio
#     pin: GPIO2
#     name: "${room} Motion"
#     device_class: motion

sensor:
  - platform: bme280
    address: 0x76
    temperature:
      name: "${room} Temperature"
      filters:
        - offset: -3.0
    pressure:
      name: "${room} Pressure"
    humidity:
      name: "${room} Humidity"
    update_interval: 60s
  - platform: bh1750
    address: 0x23
    name: "${room} Illuminance"
