substitutions:
  device_name: esp8266-node-bedroom
  friendly_name: "ESP8266 Node Bedroom"
  room: "Bedroom"

esphome:
  platform: ESP8266
  board: nodemcuv2

packages:
  base_config: !include ../../common/base.yaml
  wifi: !include ../../common/wifi.yaml
  integrated: !include ../../common/integrated.yaml
  i2c: !include ../../common/i2c.yaml

api:
  services:
    - service: set_oled_contrast
      variables:
        contrast: float
      then:
        - lambda: |-
            id(oled_display).set_contrast(contrast);
            id(oled_display).fill(COLOR_ON);

time:
  - platform: homeassistant
    id: esptime
    on_time:
      - hours: 9
        minutes: 0
        then:
          - switch.turn_on: oled_display_power
      - hours: 21
        minutes: 30
        then:
          - switch.turn_off: oled_display_power

switch:
  - platform: template
    name: "${friendly_name} — OLED Display"
    id: oled_display_power
    icon: mdi:monitor
    assumed_state: true
    optimistic: true
    turn_on_action:
      then:
        - lambda: |-
            id(oled_display).turn_on();
    turn_off_action:
      then:
        - lambda: |-
            id(oled_display).turn_off();

font:
  - file: "../../assets/fonts/din_alt.ttf"
    id: din
    size: 46

display:
  - platform: ssd1306_i2c
    id: oled_display
    model: "SH1106 128x64"
    address: 0x3C
    contrast: 60%
    rotation: 180°
    lambda: |-
      it.strftime(64, 32, id(din), TextAlign::CENTER, "%H:%M", id(esptime).now());

sensor:
  - platform: bme280
    address: 0x76
    temperature:
      name: "${room} Temperature"
      id: temperature
      filters:
        - offset: -3.0
    pressure:
      name: "${room} Pressure"
    humidity:
      name: "${room} Humidity"
      id: humidity
    update_interval: 60s
