substitutions:
  device_name: esp8266-rack-fan-controller
  friendly_name: "Rack Fan Controller"

esphome:
  platform: ESP8266
  board: d1_mini

packages:
  base_config: !include ../../common/base.yaml
  wifi: !include ../../common/wifi.yaml
  integrated: !include ../../common/integrated.yaml
  mqtt: !include ../../common/mqtt.yaml

sensor:
  - platform: mqtt_subscribe
    topic: esphome/sensor/nuc_cpu_temp
    id: nuc_cpu_temp
    on_value_range:
      - above: 72.0
        then:
          - fan.turn_on:
              id: server_rack_fan
              speed: 100
      - below: 68.0
        then:
          - fan.turn_off:
              id: server_rack_fan

output:
  - platform: esp8266_pwm
    id: mosfet
    pin: D8

fan:
  - platform: speed
    id: server_rack_fan
    name: "Server Rack Fan"
    output: mosfet
