- platform: generic
  name: "Buienradar Radarmap"
  still_image_url: "https://api.buienradar.nl/image/1.0/RadarMapBE/"

- platform: generic
  name: "ISS Map"
  still_image_url: http://staticmap.openstreetmap.de/staticmap.php?center={{ states.binary_sensor.iss.attributes.lat }},{{ states.binary_sensor.iss.attributes.long }}&zoom=4&size=865x512&maptype=mapnik&markers={{ states.binary_sensor.iss.attributes.lat }},{{ states.binary_sensor.iss.attributes.long }},lightblue
  limit_refetch_to_url_change: true
