- alias: "Power Problem Notification"
  trigger:
    platform: numeric_state
    entity_id: sensor.rpi_power_status
    above: 0
    for:
      minutes: 5
  condition: []
  action:
    - service: persistent_notification.create
      data:
        title: "\ud83d\udd0c Server Power Issue!"
        message: "Charger reported {{ states.sensor.rpi_power_status.state }}"
    - service: notify.thibault_devices
      data:
        title: "\ud83d\udd0c Server Power Issue!"
        message: "Charger reported {{ states.sensor.rpi_power_status.state }}"
