- alias: "Notify when Home Assistant Reboots/Starts"
  trigger:
    - platform: homeassistant
      event: start
  action:
    - service: notify.thibault_devices
      data:
        title: "\ud83e\udd70 Home Assistant back online!"

- alias: "Notify when Home Assistant is halting"
  trigger:
    - platform: homeassistant
      event: shutdown
  action:
    - service: notify.thibault_devices
      data:
        title: "\ud83d\ude34 Home Assistant is going down!"
