- alias: "Notify if someone is in the garage"
  trigger:
    - entity_id: binary_sensor.garage_motion
      platform: state
  condition: []
  action:
    - service: notify.thibault_devices
      data:
        title: "\ud83d\udea8 Motion detected!"
        message: "There was motion detected in the garage"
        data:
          push:
            thread-id: "automation-build-failure"
          attachment:
            url: !secret motioneye_garage_snapshot_ip
