- alias: "Alert if Trådfri remotes go below 50%"
  trigger:
  - entity_id: sensor.tradfri_remote_control
    platform: numeric_state
    below: '50'
  - entity_id: sensor.tradfri_wireless_dimmer
    platform: numeric_state
    below: '50'
  - entity_id: sensor.switch_bedlights
    platform: numeric_state
    below: '50'
  - entity_id: sensor.switch_stringlights
    platform: numeric_state
    below: '50'
  condition: []
  action:
  - service: persistent_notification.create
    data:
      title: "\ud83d\udd0b Trådfri remote low battery"
      message: "Trådfri remote {{ trigger.to_state.attributes.friendly_name }} battery level dipped depleted to {{ trigger.to_state.attributes.battery_level }} {{ trigger.to_state.attributes.unit_of_measurement }}"
