- alias: "Alert if Trådfri remotes go below 10%"
  trigger:
  - entity_id: sensor.tradfri_remote_control
    platform: numeric_state
    below: '11'
  - entity_id: sensor.tradfri_wireless_dimmer
    platform: numeric_state
    below: '11'
  condition: []
  action:
  - service: persistent_notification.create
    data:
      title: "\ud83d\udd0b Trådfri remote low battery"
      message: "A Trådfri remote's battery level dipped below 11%"
  - service: notify.thibault_devices
    data:
      title: "\ud83d\udd0b Trådfri remote low battery"
      message: "A Trådfri remote's battery level dipped below 11%"
