- platform: generic
  name: Sonoff Cam
  still_image_url: !secret sonoff_snapshot_url
  stream_source: !secret sonoff_rtsp_url

- platform: mjpeg
  name: "MJPEG Streamer"
  mjpeg_url: !secret raspberrypi_mjpeg_streamer_url
