- platform: generic
  name: "Sonoff Cam"
  still_image_url: "https://sonofcam.com"
  stream_source: !secret sonoff_rtsp_url

- platform: generic
  name: "rpi-node-kompass"
  stream_source: !secret rpi_node_kompass_rtsp_url
  still_image_url: "https://sonofcam.com"
