- platform: mqtt
  name: "Retropie Current Game"
  state_topic: "retropie/current_game"
  value_template: "{{ value_json.state }}"
  json_attributes_topic: "retropie/current_game"
  json_attributes_template: "{{ value_json.state | tojson }}"
