- platform: mqtt
  name: "Retropie Current Game"
  state_topic: "retropie/current_game"
  value_template: "{{ value_json.state.game }}"
  json_attributes_topic: "retropie/current_game"
  json_attributes_template: "{{ value_json.state | tojson }}"

- platform: mqtt
  name: "Plex Transcodes"
  icon: mdi:plex
  state_topic: "tautulli/notifications/plex/transcode"
  value_template: "{{ value_json.subject }}"
  json_attributes_topic: "tautulli/notifications/plex/transcode"
  json_attributes_template: "{{ value_json.body | tojson }}"

- platform: mqtt
  name: "Zigbee2MQTT Version"
  state_topic: "zigbee2mqtt/bridge/config"
  value_template: "{{ value_json.version }}"
  icon: mdi:zigbee

- platform: mqtt
  name: "Zigbee2MQTT Coordinator Version"
  state_topic: "zigbee2mqtt/bridge/config"
  value_template: "{{ value_json.coordinator }}"
  icon: mdi:chip

