- platform: rest
  name: "Random Cocktail"
  resource: "http://172.17.0.1:3003/random"
  scan_interval: 3600
  value_template: "{{ value_json.name }}"
  json_attributes:
    - description
    - ingredients

- platform: rest
  name: "StuBru On Air"
  resource: "http://172.17.0.1:5000/stubru"
  value_template: "{{ value_json.title }}"
  scan_interval: 900
  json_attributes:
    - description
    - startTime
    - endTime
    - image

- platform: rest
  name: "Traffic (VRT)"
  resource: "http://172.17.0.1:5000/traffic"
  value_template: "{{ value_json.teaser.trafficJamLength }}"
  scan_interval: 300
  json_attributes_path: "$.[0].teaser"
  json_attributes:
    - accidents
    - congestions
    - incidents
    - roadWorks
    - speedTraps

- platform: rest
  name: "Wireguard Status"
  resource: "http://a0d7b954-wireguard"

- platform: rest
  name: "Ambee Pollen"
  resource: https://api.ambeedata.com/latest/pollen/by-place?place=Ghent,Belgium
  scan_interval: 3600
  headers:
    content-type: "application/json"
    x-api-key: !secret ambee_api_key
  json_attributes_path: "$.data.['Risk']"
  json_attributes:
    - tree_pollen
    - grass_pollen
    - weed_pollen
