- platform: rest
  name: "Random Cocktail"
  resource: "http://172.17.0.1:3003/random"
  scan_interval: 3600
  value_template: "{{ value_json.name }}"
  json_attributes:
    - description
    - ingredients

- platform: rest
  name: "StuBru On Air"
  resource: "http://172.17.0.1:5000/stubru"
  value_template: "{{ value_json.title }}"
  scan_interval: 1800
  json_attributes:
    - description
    - startTime
    - endTime
    - image

- platform: rest
  name: "Wireguard Status"
  resource: "http://a0d7b954-wireguard"
