- platform: template
  sensors:
    day_of_week:
      friendly_name: "Day of the week"
      entity_id: sensor.time
      icon_template: mdi:calendar-outline
      value_template: >
        {{ ['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'][now().weekday()] }}

- platform: template
  sensors:
    people_home:
      friendly_name: "People at home"
      entity_id:
        - person.lotte
        - person.thibault
      unit_of_measurement: people
      value_template: >
        {{ states['person'] | selectattr('state', 'eq', 'home') | list | count }}
    people_away:
      friendly_name: "People away"
      entity_id:
        - person.lotte
        - person.thibault
      unit_of_measurement: people
      value_template: >
        {{ states['person'] | selectattr('state', 'ne', 'home') | list | count }}

- platform: template
  sensors:
    lights_on_amount:
      friendly_name: "Lights on"
      unit_of_measurement: 'on'
      value_template: >
        {{ states['light'] | selectattr('state', 'eq', 'on') | list | count }}
