- platform: template
  sensors:
    day_of_week:
      friendly_name: "Day of the week"
      icon_template: mdi:calendar-outline
      value_template: >
        {{ ['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'][now().weekday()] }}

- platform: template
  sensors:
    people_home:
      friendly_name: "People at home"
      unit_of_measurement: people
      value_template: >
        {{ states['person'] | selectattr('state', 'eq', 'home') | list | count }}
    people_away:
      friendly_name: "People away"
      unit_of_measurement: people
      value_template: >
        {{ states['person'] | selectattr('state', 'ne', 'home') | list | count }}

- platform: template
  sensors:
    lights_on_amount:
      friendly_name: "Lights on"
      unit_of_measurement: 'on'
      value_template: >
        {{ states['light'] | selectattr('state', 'eq', 'on') | list | count }}

- platform: template
  sensors:
    spotify_input_uri:
      friendly_name: "Spotify List URI"
      value_template: >-
        {% if is_state('input_select.spotify_playlists', '\U0001F3E1 Muide') %}
          spotify:playlist:0ULsscMIrT1m5AgLRdFbin
        {% elif is_state('input_select.spotify_playlists', 'Palo Cortado') %}
          spotify:playlist:36xr7VBOS2MR0ZAvTWcdmU
        {% elif is_state('input_select.spotify_playlists', 'Diner') %}
          spotify:playlist:7wxx9SFMvFnMdVj0RthRcl
        {% endif %}
    webradio_uri:
      friendly_name: "Webradio List URI"
      value_template: >-
        {% if is_state('input_select.webradio_channel', 'Stu Bru') %}
          http://icecast.vrtcdn.be/stubru-high.mp3
        {% elif is_state('input_select.webradio_channel', 'Klara') %}
          http://icecast.vrtcdn.be/klara-high.mp3
        {% elif is_state('input_select.webradio_channel', 'Klara Continuo') %}
          http://icecast.vrtcdn.be/klaracontinuo-high.mp3
        {% elif is_state('input_select.webradio_channel', 'Radio 1') %}
          http://icecast.vrtcdn.be/radio1-high.mp3
        {% elif is_state('input_select.webradio_channel', 'Worldwide FM') %}
          https://worldwidefm.out.airtime.pro/worldwidefm_b
        {% elif is_state('input_select.webradio_channel', 'NTS') %}
          https://stream-relay-geo.ntslive.net/stream
        {% elif is_state('input_select.webradio_channel', 'BBC Radio 1') %}
          http://bbcmedia.ic.llnwd.net/stream/bbcmedia_radio1_mf_p
        {% endif %}

- platform: template
  sensors:
    ambee_pollen_weed:
      icon_template: "mdi:nature"
      friendly_name: "Weed pollen"
      value_template: >
        {{ state_attr('sensor.ambee_pollen', 'weed_pollen') }}
    ambee_pollen_tree:
      icon_template: "mdi:tree-outline"
      friendly_name: "Tree pollen"
      value_template: >
        {{ state_attr('sensor.ambee_pollen', 'tree_pollen') }}
    ambee_pollen_grass:
      icon_template: "mdi:grass"
      friendly_name: "Grass pollen"
      value_template: >
        {{ state_attr('sensor.ambee_pollen', 'grass_pollen') }}
