- platform: template
  sensors:
    day_of_week:
      friendly_name: "Day of the week"
      icon_template: mdi:calendar-outline
      value_template: >
        {{ ['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'][now().weekday()] }}

- platform: template
  sensors:
    people_home:
      friendly_name: "People at home"
      unit_of_measurement: people
      value_template: >
        {{ states['person'] | selectattr('state', 'eq', 'home') | list | count }}
    people_away:
      friendly_name: "People away"
      unit_of_measurement: people
      value_template: >
        {{ states['person'] | selectattr('state', 'ne', 'home') | list | count }}

- platform: template
  sensors:
    lights_on_amount:
      friendly_name: "Lights on"
      unit_of_measurement: 'on'
      value_template: >
        {{ states['light'] | selectattr('state', 'eq', 'on') | list | count }}

- platform: template
  sensors:
    spotify_input_uri:
      friendly_name: "Spotify List URI"
      value_template: >-
        {% if is_state('input_select.spotify_playlists', '\U0001F3E1 Muide') %}
          spotify:playlist:0ULsscMIrT1m5AgLRdFbin
        {% elif is_state('input_select.spotify_playlists', 'Palo Cortado') %}
          spotify:playlist:36xr7VBOS2MR0ZAvTWcdmU
        {% elif is_state('input_select.spotify_playlists', 'Diner') %}
          spotify:playlist:7wxx9SFMvFnMdVj0RthRcl
        {% endif %}
    webradio_uri:
      friendly_name: "Webradio List URI"
      value_template: >-
        {% if is_state('input_select.webradio_channel', 'Stu Bru') %}
          http://icecast.vrtcdn.be/stubru-high.mp3
        {% elif is_state('input_select.webradio_channel', 'Klara') %}
          http://icecast.vrtcdn.be/klara-high.mp3
        {% elif is_state('input_select.webradio_channel', 'Klara Continuo') %}
          http://icecast.vrtcdn.be/klaracontinuo-high.mp3
        {% elif is_state('input_select.webradio_channel', 'Radio 1') %}
          http://icecast.vrtcdn.be/radio1-high.mp3
        {% elif is_state('input_select.webradio_channel', 'Worldwide FM') %}
          https://worldwidefm.out.airtime.pro/worldwidefm_b
        {% elif is_state('input_select.webradio_channel', 'NTS') %}
          https://stream-relay-geo.ntslive.net/stream
        {% elif is_state('input_select.webradio_channel', 'BBC Radio 1') %}
          http://bbcmedia.ic.llnwd.net/stream/bbcmedia_radio1_mf_p
        {% endif %}


- platform: template
  sensors:
    room_summary_bedroom:
      friendly_name: Bedroom summary
      value_template: >-
        {% set temperature = states('sensor.bedroom_temperature') + state_attr('sensor.bedroom_temperature', 'unit_of_measurement') %}

        {{ temperature }} / {{ state_attr('media_player.volumio_volumio_bedroom_local', 'media_title') if is_state('media_player.volumio_volumio_bedroom_local', 'paused') }}
      attribute_templates:
        is_hot: >
          {{ (states('sensor.bedroom_temperature') | int) > (state_attr('weather.weather', 'temperature') | int + 5) }}

    room_summary_living:
      friendly_name: Living summary
      value_template: >-
        {% set temperature = states('sensor.living_room_temperature') + state_attr('sensor.living_room_temperature', 'unit_of_measurement') %}

        {% if is_state('media_player.samsung_ru7100_7_series', 'on') %}
          {% if is_state_attr('media_player.samsung_ru7100_7_series', 'source', 'Playstation') %}
            {% set tv_source = state_attr('media_player.playstation_4', 'media_title') %}
          {% elif is_state_attr('media_player.samsung_ru7100_7_series', 'source', 'Plex') %}
            {% set tv_source = state_attr('media_player.plex_plex_for_samsung_tv_ue50ru7100wxxn', 'media_title') %}
          {% elif is_state_attr('media_player.samsung_ru7100_7_series', 'source', 'Telenet') %}
            {% set tv_source = 'Telenet' %}
          {% endif %}
        {% else %}
          {% set tv_source = 'TV off'%}
        {% endif %}

        {{ temperature }} / {{ tv_source }}
      attribute_templates:
        is_hot: >
          {{ (states('sensor.living_room_temperature') | int) > (state_attr('weather.weather', 'temperature') | int + 5) }}

    room_summary_studio:
      friendly_name: Studio summary
      value_template: >-
        {% set temperature = states('sensor.upstairs_temperature') + state_attr('sensor.upstairs_temperature', 'unit_of_measurement') %}

        {{ temperature }} / {{ states('sensor.discogs_random_record') }}
      attribute_templates:
        is_hot: >
          {{ (states('sensor.upstairs_temperature') | int) > (state_attr('weather.weather', 'temperature') | int + 5) }}

    room_summary_kitchen:
      friendly_name: Kitchen summary
      value_template: >-
        {% if is_state('media_player.kitchen', 'playing') %}
          {% set sonos_now_playing = state_attr('media_player.kitchen', 'media_artist') + ' - ' + state_attr('media_player.kitchen', 'media_title') %}
        {% else %}
          {% set sonos_now_playing = 'Nothing playing' %}
        {% endif %}

        {{ sonos_now_playing }}
