# This automation will use the addon to backup Hass.io snapshots
# to Google Drive every day at 10PM.
- alias: "Backup snapshots to Google Drive"
  trigger:
    platform: time
    at: "22:00:00"
  condition: []
  action:
    - service: rest_command.hassio_google_drive_backup_snapshots
    - service: rest_command.hassio_google_drive_backup_adhoc
    - service: notify.thibault_devices
      data:
        title: "\ud83d\ucdbe Creating a backup"
        message: "Uploading latest snapshot to Google Drive"
