- alias: "Notify if the Travis CI build failed for this configuration"
  trigger:
    - entity_id: sensor.travis_ci_build_status
      platform: state
      to: 'failed'
  action:
    - service: persistent_notification.create
      data:
        title: "\ud83d\uded1 Build failed!"
        message: "The pushed configuration failed to build."
    - service: notify.thibault_devices
      data:
        title: "\ud83d\uded1 Build failed!"
        message: "The pushed configuration failed to build."
        data:
          push:
            thread-id: "automation-build-failure"
            badge: 1
