- alias: "Notify if someone is in the bedroom while I'm away"
  trigger:
    - entity_id: binary_sensor.nodemcu_environment_station_pir_sensor
      platform: state
      to: 'on'

  condition:
    - platform: template
      value_template: >
        {% if is_state('person.thibault', 'home') %}
          false
        {% else %}
          true
        {% endif %}

  action:
    - service: notify.thibault_devices
      data:
        title: "\ud83d\udecf Motion detected!"
        message: "Someone entered the bedroom while you're away"
        data:
          push:
            thread-id: "automation-motion-detected"
