- alias: "Out of Office mode"
  trigger:
    - entity_id: input_boolean.out_of_office
      platform: state
      to: 'on'
  action:
    - service: rest_command.slack_set_status
      data:
        status: "Out of office"
        emoji: ":palm_tree:"
    - service: rest_command.slack_set_presence
      data:
        presence: 'away'
