- alias: "Change current theme"
  initial_state: 'on'
  hide_entity: true
  trigger:
    - platform: state
      entity_id: input_select.theme_switcher
  action:
    - service: frontend.set_theme
      data_template:
        name: "{{states('input_select.theme_switcher')}}"

- alias: "Switch to night theme automatically"
  trigger:
    - platform: sun
      event: sunset
  action:
    - service: frontend.set_theme
      data_template:
        name: "midnight"

- alias: "Switch to day theme automatically"
  trigger:
    - platform: sun
      event: sunrise
  action:
    - service: frontend.set_theme
      data_template:
        name: >
          {% if is_state("sensor.season", "autumn") %}
            season_autumn
          {% else %}
            default
          {% endif %}

- alias: "Set theme on startup"
  initial_state: 'on'
  trigger:
    platform: homeassistant
    event: start
  action:
    service: frontend.set_theme
    data:
      name: default
