- alias: "Payload debugging webhook"
  trigger:
    - platform: webhook
      webhook_id: debug-webhook
  action:
    - service: notify.thibault_devices
      data_template:
        message: >
          {{ trigger.json }} - {{ trigger.data }}
    - service: system_log.write
      data_template:
        message: >
          {{ trigger.json }} - {{ trigger.data }}
