substitutions:
  device_name: esp8266-notification-box-lotte
  friendly_name: "Notification Box (Lotte)"
  twin: "esp8266-notification-box-thib"

packages:
  base_config: !include common/base.yaml
  wifi: !include common/wifi.yaml
  integrated: !include common/integrated.yaml

esphome:
  platform: ESP8266
  board: d1_mini

switch:
  - platform: template
    name: "${friendly_name} - Red"
    turn_on_action:
      - light.turn_off: leds
      - light.turn_on:
          id: leds
          brightness: 80%
          red: 100%
          green: 85%
          blue: 43%
          effect: "Breathe"
      - delay: 10s
      - light.turn_off: leds
  - platform: template
    name: "${friendly_name} - Green"
    turn_on_action:
      - light.turn_off: leds
      - light.turn_on:
          id: leds
          brightness: 80%
          red: 87%
          green: 100%
          blue: 75%
          effect: "Breathe"
      - delay: 10s
      - light.turn_off: leds
  - platform: template
    name: "${friendly_name} - Orange"
    turn_on_action:
      - light.turn_off: leds
      - light.turn_on:
          id: leds
          brightness: 80%
          red: 100%
          green: 64%
          blue: 28%
          effect: "Breathe"
      - delay: 10s
      - light.turn_off: leds

binary_sensor:
  - platform: gpio
    id: button_brown
    pin: D6
    filters:
      - delayed_on: 20ms
    on_press:
      - light.turn_off: leds
      - light.turn_on:
          id: leds
          brightness: 80%
          red: 100%
          green: 85%
          blue: 43%
      - homeassistant.service:
          service: switch.turn_on
          data:
            entity_id: "switch.${twin}_red"
      - delay: 1s
      - light.turn_off: leds
  - platform: gpio
    id: button_yellow
    pin: D7
    filters:
      - delayed_on: 20ms
    on_press:
      - light.turn_off: leds
      - light.turn_on:
          id: leds
          brightness: 80%
          red: 87%
          green: 100%
          blue: 75%
      - homeassistant.service:
          service: switch.turn_on
          data:
            entity_id: "switch.${twin}_green"
      - delay: 1s
      - light.turn_off: leds
  - platform: gpio
    id: button_orange
    pin: D8
    filters:
      - delayed_on: 20ms
    on_press:
      - light.turn_off: leds
      - light.turn_on:
          id: leds
          brightness: 80%
          red: 100%
          green: 64%
          blue: 28%
      - homeassistant.service:
          service: switch.turn_on
          data:
            entity_id: "switch.${twin}_orange"
      - delay: 1s
      - light.turn_off: leds

light:
  - platform: fastled_clockless
    id: leds
    pin: D4
    chipset: WS2812B
    num_leds: 4
    rgb_order: GRB
    effects:
      - automation:
          name: Breathe
          sequence:
            - delay: 1s
            - light.dim_relative:
                id: leds
                relative_brightness: 50%
                transition_length: 4s
            - delay: 1s
            - light.dim_relative:
                id: leds
                relative_brightness: -50%
                transition_length: 4s
