substitutions:
  device_name: esp8266_volumio_bureau
  friendly_name: "Volumio Bureau"

esphome:
  platform: ESP8266
  board: d1_mini

packages:
  base_config: !include ../../common/base.yaml
  wifi: !include ../../common/wifi.yaml
  integrated: !include ../../common/integrated.yaml
  mqtt: !include ../../common/mqtt.yaml
  i2c: !include ../../common/i2c.yaml

display:
  - platform: lcd_pcf8574
    dimensions: 16x2
    address: 0x27
    lambda: |-
      it.printf(0, 0, "%s", id(volumio_current_track).state.c_str());

text_sensor:
  - platform: mqtt_subscribe
    name: "Current track"
    id: volumio_current_track
    topic: go-volumio-mqtt/volumio-bureau/track
