esphome:
  name: wemos_sound_level_detector
  platform: ESP8266
  board: d1_mini

<<: !include common/base.yaml

# BELOW WILL READ OUT THE ANALOG SIGNAL
# sensor:
  # - platform: adc
  #   pin: A0
  #   name: "Sound level"
  #   update_interval: 1s
  #   filters:
  #     - multiply: 3.3

# DEBOUNCED FOR 1S BECAUSE THE TRIGGER PERIOD IS VERY SHORT
binary_sensor:
  - platform: gpio
    pin: D2
    name: "Sound level"
    filters:
      - delayed_off: 1s
