substitutions:
  device_name: esp8266_ws8212b_dj_booth_led_strip
  friendly_name: "ESP8266 WS8212B DJ Booth Led Strip"

esphome:
  name: "${device_name}"
  platform: ESP8266
  board: nodemcuv2

<<: !include common.yaml

binary_sensor:
  - platform: status
    name: "${friendly_name} — Status"

sensor:
  - platform: uptime
    name: "${friendly_name} — Uptime"
  - platform: wifi_signal
    name: "${friendly_name} — Signal"
    update_interval: 60s

light:
  - platform: fastled_clockless
    name: "${friendly_name}"
    chipset: WS2812B
    pin: D4
    rgb_order: GRB # Valid values are RGB, RBG, GRB, GBR, BRG and BGR. Defaults to RGB. GRB
    num_leds: 160
    effects:
      - addressable_rainbow:
      - addressable_color_wipe:
      - addressable_scan:
      - addressable_twinkle:
