substitutions:
  device_name: lsc-e27-bulb-bedroom
  friendly_name: "LSC Smart Connect E27 Filament LED"

esphome:
  platform: ESP8266
  board: esp01_1m

packages:
  base_config: !include ../../common/base.yaml
  wifi: !include ../../common/wifi.yaml
  integrated: !include ../../common/integrated.yaml

light:
  - platform: cwww
    name: "${friendly_name}"
    cold_white: output_cold_white
    warm_white: output_warm_white
    cold_white_color_temperature: "3500 K"
    warm_white_color_temperature: "2000 K"

output:
  - platform: esp8266_pwm
    id: output_cold_white
    pin: 14
  - platform: esp8266_pwm
    id: output_warm_white
    pin: 12
