- platform: template
  sensors:
    calendar_agenda:
      friendly_name: 'Agenda'
      entity_id: calendar.agenda
      value_template: >
        {% if is_state('calendar.agenda', 'on') %}
          {{ states.calendar.agenda.attributes.message }}
        {% endif %}

    calendar_tasks:
      friendly_name: 'Taken'
      entity_id: calendar.taken
      value_template: >
        {% if is_state('calendar.taken', 'on') %}
          {{ states.calendar.taken.attributes.message }}
        {% endif %}

    calendar_events:
      friendly_name: 'Evenementen'
      entity_id: calendar.evenementen
      value_template: >
        {% if is_state('calendar.evenementen', 'on') %}
          {{ states.calendar.evenementen.attributes.message }}
        {% endif %}

    calendar_facebook:
      friendly_name: 'Facebook'
      entity_id: calendar.thibault_maekelberghs_facebook_events
      value_template: >
        {% if is_state('calendar.thibault_maekelberghs_facebook_events', 'on') %}
          {{ states.calendar.thibault_maekelberghs_facebook_events.attributes.message }}
        {% endif %}


    calendar_lotte__thib:
      friendly_name: 'Lotte & Thib'
      entity_id: calendar.lot__thib
      value_template: >
        {% if is_state('calendar.lot__thib', 'on') %}
          {{ states.calendar.lot__thib.attributes.message }}
        {% endif %}
