- platform: darksky
  name: "Dark Sky weather"
  api_key: !secret dark_sky_api_key
  language: 'nl'
  forecast:
    - 1
    - 2
    - 3
    - 4
    - 5
  monitored_conditions:
    - summary
    - precip_type
    - precip_intensity
    - precip_probability
    - temperature
    - apparent_temperature
    - wind_speed
    - cloud_cover
    - minutely_summary
    - hourly_summary
    - daily_summary
    - precip_intensity_max
    - icon
    - nearest_storm_distance
    - nearest_storm_bearing
    - humidity
    - temperature_high
    - temperature_low
    - apparent_temperature
    - apparent_temperature_high
    - apparent_temperature_low
    - wind_bearing
    - precip_accumulation
    - uv_index
    - daily_summary
    - pressure
    - visibility
  scan_interval:
    minutes: 10
