- platform: glances
  host: !secret host_panorama
  resources:
    - disk_use_percent
    - disk_free
    - memory_use_percent
    - processor_load

- platform: glances
  host: !secret host_nextcloudpi
  resources:
    - disk_use_percent
    - disk_free
    - memory_use_percent
    - processor_load

- platform: glances
  host: !secret host_tresor
  resources:
    - disk_use_percent
    - disk_free
    - memory_use_percent
    - processor_load
