# Monstera Deliciosa
- platform: mqtt
  name: monstera_deliciosa_moisture
  state_topic: homeassistant/sensor/monstera/state
  value_template: '{{ value_json.moisture }}'
  unit_of_measurement: '%'
- platform: mqtt
  name: monstera_deliciosa_battery
  state_topic: homeassistant/sensor/monstera/state
  value_template: '{{ value_json.battery }}'
  unit_of_measurement: '%'
- platform: mqtt
  name: monstera_deliciosa_temperature
  state_topic: homeassistant/sensor/monstera/state
  value_template: '{{ value_json.temperature }}'
  unit_of_measurement: '°C'
- platform: mqtt
  name: monstera_deliciosa_conductivity
  state_topic: homeassistant/sensor/monstera/state
  value_template: '{{ value_json.conductivity }}'
  unit_of_measurement: 'µS/cm'
- platform: mqtt
  name: monstera_deliciosa_brightness
  state_topic: homeassistant/sensor/monstera/state
  value_template: '{{ value_json.light }}'
  unit_of_measurement: 'lux'

# Ficus Elastica
- platform: mqtt
  name: ficus_elastica_moisture
  state_topic: homeassistant/sensor/ficus/state
  value_template: '{{ value_json.moisture }}'
  unit_of_measurement: '%'
- platform: mqtt
  name: ficus_elastica_battery
  state_topic: homeassistant/sensor/ficus/state
  value_template: '{{ value_json.battery }}'
  unit_of_measurement: '%'
- platform: mqtt
  name: ficus_elastica_temperature
  state_topic: homeassistant/sensor/ficus/state
  value_template: '{{ value_json.temperature }}'
  unit_of_measurement: '°C'
- platform: mqtt
  name: ficus_elastica_conductivity
  state_topic: homeassistant/sensor/ficus/state
  value_template: '{{ value_json.conductivity }}'
  unit_of_measurement: 'µS/cm'
- platform: mqtt
  name: ficus_elastica_brightness
  state_topic: homeassistant/sensor/ficus/state
  value_template: '{{ value_json.light }}'
  unit_of_measurement: 'lux'
