- platform: mqtt
  name: bedroom_temperature
  state_topic: homeassistant/rpi-zero-w-sensors/dht/temperature
  unit_of_measurement: '°C'
- platform: mqtt
  name: bedroom_humidity
  state_topic: homeassistant/rpi-zero-w-sensors/dht/humidity
  unit_of_measurement: '%'

# Monstera Deliciosa
- platform: mqtt
  name: monstera_deliciosa_moisture
  state_topic: homeassistant/sensor/monstera/state
  value_template: '{{ value_json.moisture }}'
  unit_of_measurement: '%'
- platform: mqtt
  name: monstera_deliciosa_battery
  state_topic: homeassistant/sensor/monstera/state
  value_template: '{{ value_json.battery }}'
  unit_of_measurement: '%'
- platform: mqtt
  name: monstera_deliciosa_temperature
  state_topic: homeassistant/sensor/monstera/state
  value_template: '{{ value_json.temperature }}'
  unit_of_measurement: '°C'
- platform: mqtt
  name: monstera_deliciosa_conductivity
  state_topic: homeassistant/sensor/monstera/state
  value_template: '{{ value_json.conductivity }}'
  unit_of_measurement: 'µS/cm'
- platform: mqtt
  name: monstera_deliciosa_brightness
  state_topic: homeassistant/sensor/monstera/state
  value_template: '{{ value_json.light }}'
  unit_of_measurement: 'lux'

# Calathea Leopardina
- platform: mqtt
  name: calathea_leopardina_moisture
  state_topic: homeassistant/sensor/calathea/state
  value_template: '{{ value_json.moisture }}'
  unit_of_measurement: '%'
- platform: mqtt
  name: calathea_leopardina_battery
  state_topic: homeassistant/sensor/calathea/state
  value_template: '{{ value_json.battery }}'
  unit_of_measurement: '%'
- platform: mqtt
  name: calathea_leopardina_temperature
  state_topic: homeassistant/sensor/calathea/state
  value_template: '{{ value_json.temperature }}'
  unit_of_measurement: '°C'
- platform: mqtt
  name: calathea_leopardina_conductivity
  state_topic: homeassistant/sensor/calathea/state
  value_template: '{{ value_json.conductivity }}'
  unit_of_measurement: 'µS/cm'
- platform: mqtt
  name: calathea_leopardina_brightness
  state_topic: homeassistant/sensor/calathea/state
  value_template: '{{ value_json.light }}'
  unit_of_measurement: 'lux'
