# DHT11
- platform: mqtt
  name: "Bedroom Temperature"
  icon: mdi:thermometer
  state_topic: nodemcu-bedroom/tele/SENSOR
  unit_of_measurement: '°C'
  value_template: '{{ value_json.DHT11.Temperature }}'
  availability_topic: nodemcu-bedroom/tele/LWT
  payload_available: "Online"
  payload_not_available: "Offline"
- platform: mqtt
  name: "Bedroom Humidity"
  icon: mdi:water-percent
  state_topic: nodemcu-bedroom/tele/SENSOR
  unit_of_measurement: '%'
  value_template: '{{ value_json.DHT11.Humidity }}'
  availability_topic: nodemcu-bedroom/tele/LWT
  payload_available: "Online"
  payload_not_available: "Offline"

# HP Printer Ink levels
- platform: mqtt
  name: printer_ink_level_cyan
  state_topic: homeassistant/sensor/hp-printer/color-cyan
  icon: mdi:alpha-c-box
  unit_of_measurement: '%'
- platform: mqtt
  state_topic: homeassistant/sensor/hp-printer/color-magenta
  icon: mdi:alpha-m-box
  unit_of_measurement: '%'
- platform: mqtt
  name: printer_ink_level_yellow
  state_topic: homeassistant/sensor/hp-printer/color-yellow
  icon: mdi:alpha-y-box
  unit_of_measurement: '%'
- platform: mqtt
  name: printer_ink_level_black
  state_topic: homeassistant/sensor/hp-printer/color-black
  icon: mdi:alpha-k-box
  unit_of_measurement: '%'

# Monstera Deliciosa
- platform: mqtt
  name: monstera_deliciosa_moisture
  state_topic: homeassistant/sensor/monsteradeliciosa/state
  value_template: '{{ value_json.moisture }}'
  unit_of_measurement: '%'
- platform: mqtt
  name: monstera_deliciosa_battery
  state_topic: homeassistant/sensor/monsteradeliciosa/state
  value_template: '{{ value_json.battery }}'
  unit_of_measurement: '%'
- platform: mqtt
  name: monstera_deliciosa_temperature
  state_topic: homeassistant/sensor/monsteradeliciosa/state
  value_template: '{{ value_json.temperature }}'
  unit_of_measurement: '°C'
- platform: mqtt
  name: monstera_deliciosa_conductivity
  state_topic: homeassistant/sensor/monsteradeliciosa/state
  value_template: '{{ value_json.conductivity }}'
  unit_of_measurement: 'µS/cm'
- platform: mqtt
  name: monstera_deliciosa_brightness
  state_topic: homeassistant/sensor/monsteradeliciosa/state
  value_template: '{{ value_json.light }}'
  unit_of_measurement: 'lux'

# Ficus Elastica
- platform: mqtt
  name: ficus_elastica_moisture
  state_topic: homeassistant/sensor/ficuselastica/state
  value_template: '{{ value_json.moisture }}'
  unit_of_measurement: '%'
- platform: mqtt
  name: ficus_elastica_battery
  state_topic: homeassistant/sensor/ficuselastica/state
  value_template: '{{ value_json.battery }}'
  unit_of_measurement: '%'
- platform: mqtt
  name: ficus_elastica_temperature
  state_topic: homeassistant/sensor/ficuselastica/state
  value_template: '{{ value_json.temperature }}'
  unit_of_measurement: '°C'
- platform: mqtt
  name: ficus_elastica_conductivity
  state_topic: homeassistant/sensor/ficuselastica/state
  value_template: '{{ value_json.conductivity }}'
  unit_of_measurement: 'µS/cm'
- platform: mqtt
  name: ficus_elastica_brightness
  state_topic: homeassistant/sensor/ficuselastica/state
  value_template: '{{ value_json.light }}'
  unit_of_measurement: 'lux'
