# DHT11
- platform: mqtt
  name: "Bedroom Temperature"
  state_topic: homeassistant/nodemcu-bedroom/SENSOR
  unit_of_measurement: '°C'
  value_template: '{{ value_json.DHT11.Temperature }}'
  availability_topic: homeassistant/nodemcu-bedroom/LWT
  payload_available: "Online"
  payload_not_available: "Offline"
- platform: mqtt
  name: "Bedroom Humidity"
  state_topic: homeassistant/nodemcu-bedroom/SENSOR
  unit_of_measurement: '%'
  value_template: '{{ value_json.DHT11.Humidity }}'
  availability_topic: homeassistant/nodemcu-bedroom/LWT
  payload_available: "Online"
  payload_not_available: "Offline"

# HP Printer Ink levels
- platform: mqtt
  name: printer_ink_level_cyan
  state_topic: homeassistant/sensor/hp-printer/color-cyan
  friendly_name: "Ink level (Cyan)"
  icon: mdi:alpha-c-box
  unit_of_measurement: '%'
- platform: mqtt
  name: printer_ink_level_magenta
  state_topic: homeassistant/sensor/hp-printer/color-magenta
  friendly_name: "Ink level (Magenta)"
  icon: mdi:alpha-m-box
  unit_of_measurement: '%'
- platform: mqtt
  name: printer_ink_level_yellow
  state_topic: homeassistant/sensor/hp-printer/color-yellow
  friendly_name: "Ink level (Yellow)"
  icon: mdi:alpha-y-box
  unit_of_measurement: '%'
- platform: mqtt
  name: printer_ink_level_black
  state_topic: homeassistant/sensor/hp-printer/color-black
  friendly_name: "Ink level (Keycolor)"
  icon: mdi:alpha-k-box
  unit_of_measurement: '%'

# Monstera Deliciosa
- platform: mqtt
  name: monstera_deliciosa_moisture
  state_topic: homeassistant/sensor/monsteradeliciosa/state
  value_template: '{{ value_json.moisture }}'
  unit_of_measurement: '%'
- platform: mqtt
  name: monstera_deliciosa_battery
  state_topic: homeassistant/sensor/monsteradeliciosa/state
  value_template: '{{ value_json.battery }}'
  unit_of_measurement: '%'
- platform: mqtt
  name: monstera_deliciosa_temperature
  state_topic: homeassistant/sensor/monsteradeliciosa/state
  value_template: '{{ value_json.temperature }}'
  unit_of_measurement: '°C'
- platform: mqtt
  name: monstera_deliciosa_conductivity
  state_topic: homeassistant/sensor/monsteradeliciosa/state
  value_template: '{{ value_json.conductivity }}'
  unit_of_measurement: 'µS/cm'
- platform: mqtt
  name: monstera_deliciosa_brightness
  state_topic: homeassistant/sensor/monsteradeliciosa/state
  value_template: '{{ value_json.light }}'
  unit_of_measurement: 'lux'

# Monstera Monkey Mask
- platform: mqtt
  name: monstera_monkey_mask_moisture
  state_topic: homeassistant/sensor/monsteramonkeymask/state
  value_template: '{{ value_json.moisture }}'
  unit_of_measurement: '%'
- platform: mqtt
  name: monstera_monkey_mask_battery
  state_topic: homeassistant/sensor/monsteramonkeymask/state
  value_template: '{{ value_json.battery }}'
  unit_of_measurement: '%'
- platform: mqtt
  name: monstera_monkey_mask_temperature
  state_topic: homeassistant/sensor/monsteramonkeymask/state
  value_template: '{{ value_json.temperature }}'
  unit_of_measurement: '°C'
- platform: mqtt
  name: monstera_monkey_mask_conductivity
  state_topic: homeassistant/sensor/monsteramonkeymask/state
  value_template: '{{ value_json.conductivity }}'
  unit_of_measurement: 'µS/cm'
- platform: mqtt
  name: monstera_monkey_mask_brightness
  state_topic: homeassistant/sensor/monsteramonkeymask/state
  value_template: '{{ value_json.light }}'
  unit_of_measurement: 'lux'
