- platform: rest
  resource: !secret discogs_random_record_lambda
  name: "Discogs Random Record"
  json_attributes:
    - basic_information
  value_template: "{{ value_json.record.basic_information.title }} - {{ value_json.record.basic_information.title }}"
