- platform: rest
  name: "Travis CI Build Status"
  resource: https://api.travis-ci.org/repos/thibmaek/homeassistant-conf/builds
  headers:
    Accept: application/vnd.travis-ci.2+json
  value_template: "{{ value_json.builds[0].state }}"
