- platform: rest
  icon: mdi:record-player
  scan_interval: 1800
  resource: !secret discogs_random_record_lambda
  name: "Discogs Random Record"
  json_attributes:
    - basic_information
  value_template: "{{ value_json.record.basic_information.title }} - {{ value_json.record.basic_information.title }}"
