- platform: template
  sensors:
    day_of_week:
      friendly_name: "Day of the week"
      entity_id: sensor.time
      icon_template: mdi:calendar-outline
      value_template: >
        {{ ['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'][now().weekday()] }}
