esphome:
  name: esp32_camera
  platform: ESP32
  board: esp-wrover-kit

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:
api:
ota:

switch:
  - platform: restart
    name: "ESP32 Camera Restart"
    id: restart

esp32_camera:
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32

  name: ESP32 AI Thinker

time:
  - platform: sntp
    on_time:
      - seconds: 0
        minutes: 30
        hours: 7
        days_of_week: '*'
        then:
          - switch.toggle: restart
