substitutions:
  device_name: "esp32_plant_monitor"
  friendly_name: "ESP32 Plant Monitor"
  plant_one: "Monstera Deliciosa (Inkom)"
  plant_two: "Calathea (Living)"

<<: !include common.yaml

esphome:
  name: "${device_name}"
  platform: ESP32
  board: esp32dev

esp32_ble_tracker:

binary_sensor:
  - platform: status
    name: "${friendly_name} — Status"

sensor:
  - platform: uptime
    name: "${friendly_name} — Uptime"

  - platform: wifi_signal
    name: "${friendly_name} — Signal"
    update_interval: 60s

  - platform: xiaomi_hhccjcy01
    mac_address: 'C4:7C:8D:65:CA:76'
    temperature:
      name: "${plant_one} — Temperature"
    moisture:
      name: "${plant_one} — Moisture"
    illuminance:
      name: "${plant_one} — Illuminance"
    conductivity:
      name: "${plant_one} — Soil Conductivity"
    battery_level:
      name: "${plant_one} — Battery Level"

  - platform: xiaomi_hhccjcy01
    mac_address: 'C4:7C:8D:66:56:FC'
    temperature:
      name: "${plant_two} Temperature"
    moisture:
      name: "${plant_two} Moisture"
    illuminance:
      name: "${plant_two} Illuminance"
    conductivity:
      name: "${plant_two} Soil Conductivity"
    battery_level:
      name: "${plant_two} Battery Level"
