substitutions:
  device_name: esp32_seedling_monitor
  friendly_name: ESP32 Seedling Monitor

esphome:
  name: "${device_name}"
  platform: ESP32
  board: esp32dev

packages:
  base_config: !include common/base.yaml
  wifi: !include common/wifi.yaml
  integrated: !include common/integrated.yaml

interval:
  - interval: 60min
    then:
      - switch.toggle: soil_sensor_power

binary_sensor:
  - platform: gpio
    name: "${friendly_name} — Dry Soil"
    device_class: moisture
    pin: GPIO13

switch:
  - platform: gpio
    id: soil_sensor_power
    name: "${friendly_name} — Soil Sensor Power"
    pin:
      number: GPIO33
      inverted: false

sensor:
  - platform: dht
    model: DHT11
    pin: GPIO23
    temperature:
      name: "${friendly_name} — Temperature"
    humidity:
      name: "${friendly_name} — Humidity"
    update_interval: 60s
