substitutions:
  device_name: esp8266_node_bedroom
  friendly_name: "ESP8226 Node Bedroom"

packages:
  base_config: !include common/base.yaml
  wifi: !include common/wifi.yaml
  mqtt: !include common/mqtt.yaml

esphome:
  platform: ESP32
  board: nodemcu-32s

binary_sensor:
  - platform: gpio
    name: "Top Button"
    pin:
      number: GPIO25
      mode: INPUT_PULLUP
      inverted: true

  - platform: gpio
    name: "Button 1"
    pin:
      number: GPIO15
      mode: INPUT_PULLUP
      inverted: true
  - platform: gpio
    name: "Button 2"
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: true
  - platform: gpio
    name: "Button 3"
    pin:
      number: GPIO4
      mode: INPUT_PULLUP
      inverted: true
  - platform: gpio
    name: "Button 4"
    pin:
      number: GPIO16
      mode: INPUT_PULLUP
      inverted: true
  - platform: gpio
    name: "Button 5"
    pin:
      number: GPIO17
      mode: INPUT_PULLUP
      inverted: true
  - platform: gpio
    name: "Button 6"
    pin:
      number: GPIO5
      mode: INPUT_PULLUP
      inverted: true
  - platform: gpio
    name: "Button 7"
    pin:
      number: GPIO18
      mode: INPUT_PULLUP
      inverted: true
  - platform: gpio
    name: "Button 8"
    pin:
      number: GPIO19
      mode: INPUT_PULLUP
      inverted: true
  - platform: gpio
    name: "Button 9"
    pin:
      number: GPIO21
      mode: INPUT_PULLUP
      inverted: true
  - platform: gpio
    name: "Button 10"
    pin:
      number: GPIO22
      mode: INPUT_PULLUP
      inverted: true
  - platform: gpio
    name: "Button 11"
    pin:
      number: GPIO23
      mode: INPUT_PULLUP
      inverted: true
  - platform: gpio
    name: "Button 12"
    pin:
      number: GPIO13
      mode: INPUT_PULLUP
      inverted: true
  - platform: gpio
    name: "Button 13"
    pin:
      number: GPIO12
      mode: INPUT_PULLUP
      inverted: true
  - platform: gpio
    name: "Button 14"
    pin:
      number: GPIO14
      mode: INPUT_PULLUP
      inverted: true
  - platform: gpio
    name: "Button 15"
    pin:
      number: GPIO27
      mode: INPUT_PULLUP
      inverted: true
  - platform: gpio
    name: "Button 16"
    pin:
      number: GPIO26
      mode: INPUT_PULLUP
      inverted: true

light:
  - platform: fastled_clockless
    name: "Color LED"
    pin: GPIO33
    chipset: WS2811
    num_leds: 1
    rgb_order: BRG

sensor:
  - platform: adc
    name: "Potentiometer"
    pin: GPIO34
  - platform: rotary_encoder
    name: "Rotary Encoder"
    pin_a: GPIO23
    pin_b: GPIO22
    pin_reset: GPIO21
    on_clockwise:
      - logger.log: "Turned Clockwise"
    on_anticlockwise:
      - logger.log: "Turned Counterclockwise"
