substitutions:
  device_name: esp8266_node_upstairs
  friendly_name: "ESP8266 Node Upstairs"
  room: Upstairs

esphome:
  name: "${device_name}"
  platform: ESP8266
  board: d1_mini

<<: !include common/base.yaml
<<: !include common/i2c.yaml
<<: !include common/info_sensors.yaml

api:
  services:
    - service: set_oled_brightness
      variables:
        brightness: float
      then:
        - lambda: |-
            id(oled_display).set_brightness(brightness);
            id(oled_display).fill(COLOR_ON);

binary_sensor:
  - platform: status
    name: "${friendly_name} — Status"

time:
  - platform: homeassistant
    id: esptime
    on_time:
      - hours: 9
        minutes: 30
        then:
          - switch.turn_on: oled_display_backlight
      - hours: 21
        minutes: 30
        then:
          - switch.turn_off: oled_display_backlight

switch:
  - platform: template
    name: "${friendly_name} — Display Backlight"
    id: oled_display_backlight
    icon: mdi:brightness-6
    assumed_state: true
    optimistic: true
    turn_on_action:
      then:
        - lambda: |-
            id(oled_display).set_brightness(1);
            id(oled_display).fill(COLOR_ON);
    turn_off_action:
      then:
        - lambda: |-
            id(oled_display).set_brightness(0);
            id(oled_display).fill(COLOR_OFF);

font:
  - file: 'assets/fonts/arial.ttf'
    id: arial
    size: 20
  - file: 'assets/fonts/arial.ttf'
    id: arial_sm
    size: 14

display:
  - platform: ssd1306_i2c
    id: oled_display
    model: "SH1106 128x32"
    address: 0x3C
    brightness: 60%
    rotation: 180°
    lambda: |-
      it.strftime(2, 32, id(arial), TextAlign::BASELINE_LEFT, "%H:%M", id(esptime).now());

      if (id(temperature).has_state()) {
        it.printf(127, 0, id(arial_sm), TextAlign::TOP_RIGHT, "%.1f°", id(temperature).state);
      }

      if (id(humidity).has_state()) {
        it.printf(127, 28, id(arial_sm), TextAlign::BASELINE_RIGHT, "%.1f%%", id(humidity).state);
      }

light:
  - platform: rgb
    id: rgb_led
    red: output_red
    green: output_green
    blue: output_blue

output:
  - platform: esp8266_pwm
    id: output_red
    pin: D5
  - platform: esp8266_pwm
    id: output_green
    pin: D6
  - platform: esp8266_pwm
    id: output_blue
    pin: D7

sensor:
  - platform: uptime
    name: "${friendly_name} — Uptime"
  - platform: wifi_signal
    name: "${friendly_name} — Signal"
    update_interval: 60s
  - platform: bme280
    address: 0x76
    temperature:
      name: "${room} Temperature"
      id: temperature
      filters:
        - offset: -3.0
      on_value_range:
        - above: 29.0
          then:
            - light.turn_on:
                id: rgb_led
                red: 1.0
                green: 0
                blue: 0
        - below: 28.9
          then:
            - light.turn_on:
                id: rgb_led
                red: 0
                green: 1.0
                blue: 0
    pressure:
      name: "${room} Pressure"
    humidity:
      name: "${room} Humidity"
      id: humidity
    update_interval: 60s
