substitutions:
  device_name: esp8266_pir_studio
  friendly_name: ESP8266 PIR Studio

esphome:
  name: "${device_name}"
  platform: ESP8266
  board: d1_mini

<<: !include common/base.yaml
<<: !include common/info_sensors.yaml

binary_sensor:
  - platform: status
    name: "${friendly_name} — Status"
  - platform: gpio
    name: "${friendly_name} — Motion"
    pin: D4
    device_class: motion


sensor:
  - platform: uptime
    name: "${friendly_name} — Uptime"
  - platform: wifi_signal
    name: "${friendly_name} — Signal"
