substitutions:
  device_name: esp8266_desk
  friendly_name: ESP8266 Desk

packages:
  base_config: !include common/base.yaml
  wifi: !include common/wifi.yaml
  integrated: !include common/integrated.yaml

esphome:
  platform: ESP8266
  board: d1_mini

sensor:
  - platform: ultrasonic
    trigger_pin: GPIO5
    echo_pin: GPIO4
    name: "Ultrasonic Sensor"
