substitutions:
  device_name: esp8266_node_kitchen
  friendly_name: "ESP8266 Node Kitchen"
  room: Kitchen

esphome:
  name: "${device_name}"
  platform: ESP8266
  board: d1_mini

<<: !include common/base.yaml
<<: !include common/info_sensors.yaml
<<: !include common/i2c.yaml

binary_sensor:
  - platform: status
    name: "${friendly_name} — Status"
  - platform: gpio
    pin: GPIO2
    name: "${room} Motion"
    device_class: motion

sensor:
  - platform: uptime
    name: "${friendly_name} — Uptime"
  - platform: wifi_signal
    name: "${friendly_name} — Signal"
    update_interval: 60s
  - platform: bme280
    address: 0x76
    temperature:
      name: "${room} Temperature"
      filters:
        - offset: -3.0
    pressure:
      name: "${room} Pressure"
    humidity:
      name: "${room} Humidity"
    update_interval: 60s
  - platform: bh1750
    address: 0x23
    name: "${room} Illuminance"
