substitutions:
  device_name: esp8226_buzzer
  friendly_name: ESP8266 Buzzer

packages:
  base_config: !include common/base.yaml
  wifi: !include common/wifi.yaml
  integrated: !include common/integrated.yaml

esphome:
  platform: ESP8266
  board: d1_mini

output:
  - platform: esp8266_pwm
    pin: D1
    id: 'buzzer'

api:
  services:
    - service: buzz
      then:
        - output.esp8266_pwm.set_frequency:
            id: buzzer
            frequency: 800Hz
        - output.set_level:
            id: buzzer
            level: 50%
        - delay: 120ms
        - output.turn_off: buzzer
        - delay: 200ms
        - output.esp8266_pwm.set_frequency:
            id: buzzer
            frequency: 1000Hz
        - output.set_level:
            id: buzzer
            level: 50%
        - delay: 120ms
        - output.turn_off: buzzer
