substitutions:
  device_name: esp8266_volumio_bureau
  friendly_name: "Volumio Bureau"

esphome:
  name: "${device_name}"
  platform: ESP8266
  board: d1_mini

<<: !include common/base.yaml

i2c:
  scan: true

binary_sensor:
  - platform: status
    name: "${friendly_name} — Status"

display:
  - platform: lcd_pcf8574
    dimensions: 16x2
    address: 0x27
    lambda: |-
      it.printf(0, 0, "%s", "Volumio");

sensor:
  - platform: uptime
    name: "${friendly_name} — Uptime"
  - platform: wifi_signal
    name: "${friendly_name} — Signal"

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "${friendly_name} — IP"
  - platform: version
    icon: mdi:package-variant
    name: "${friendly_name} — Version"
