substitutions:
  device_name: esp8266_node_upstairs
  friendly_name: "ESP8266 Node Upstairs"
  room: Upstairs

esphome:
  name: "${device_name}"
  platform: ESP8266
  board: nodemcuv2

<<: !include common.yaml

i2c:
  scan: True

binary_sensor:
  - platform: status
    name: "${friendly_name} — Status"
  - platform: gpio
    pin: D6
    name: "${room} Motion"
    device_class: motion

sensor:
  - platform: uptime
    name: "${friendly_name} — Uptime"
  - platform: wifi_signal
    name: "${friendly_name} — Signal"
    update_interval: 60s
  - platform: bh1750
    name: "${room} Illuminance"
    update_interval: 60s
  - platform: bme280
    address: 0x76
    temperature:
      name: "${room} Temperature"
    pressure:
      name: "${room} Pressure"
    humidity:
      name: "${room} Humidity"
    update_interval: 60s
