substitutions:
  device_name: esp8266_node_bedroom
  friendly_name: "ESP8226 Node Bedroom"
  room: Bedroom

<<: !include common.yaml

esphome:
  name: "${device_name}"
  platform: ESP8266
  board: d1_mini

i2c:
  scan: True

binary_sensor:
  - platform: status
    name: "${friendly_name} — Status"

sensor:
  - platform: uptime
    name: "${friendly_name} — Uptime"
  - platform: wifi_signal
    name: "${friendly_name} — Signal"
    update_interval: 60s
  - platform: bme280
    address: 0x76
    temperature:
      name: "${room} Temperature"
    pressure:
      name: "${room} Pressure"
    humidity:
      name: "${room} Humidity"
    update_interval: 60s
