esphome:
  name: esp8266_node_upstairs
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:
ota:
api:

i2c:
  scan: True

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "ESP8266 Node Upstairs IP"
    ssid:
      name: "ESP8266 Node Upstairs SSID"
    bssid:
      name: "ESP8266 Node Upstairs BSSID"

binary_sensor:
  - platform: gpio
    pin: D6
    name: "Upstairs Motion"
    device_class: motion

sensor:
  - platform: wifi_signal
    name: "ESP8266 Node Upstairs Signal"
    update_interval: 60s

  - platform: bh1750
    name: "Upstairs Illuminance"
    update_interval: 60s

  - platform: bme280
    address: 0x76
    temperature:
      name: "Upstairs Temperature"
    pressure:
      name: "Upstairs Pressure"
    humidity:
      name: "Upstairs Humidity"
    update_interval: 60s
