esphome:
  name: esp8266_node_bedroom
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:
ota:
api:

i2c:
  scan: True

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "ESP8266 Node Bedroom IP"
    ssid:
      name: "ESP8266 Node Bedroom SSID"
    bssid:
      name: "ESP8266 Node Bedroom BSSID"

sensor:
  - platform: wifi_signal
    name: "ESP8266 Node Bedroom Signal"
    update_interval: 60s

  - platform: bme280
    address: 0x76
    temperature:
      name: "Bedroom Temperature"
    pressure:
      name: "Bedroom Pressure"
    humidity:
      name: "Bedroom Humidity"
    update_interval: 60s
