substitutions:
  device_name: esp8266_node_upstairs
  friendly_name: "ESP8266 Node Upstairs"
  room: Upstairs

esphome:
  name: "${device_name}"
  platform: ESP8266
  board: d1_mini

<<: !include common.yaml

i2c:
  scan: True

binary_sensor:
  - platform: status
    name: "${friendly_name} — Status"

light:
  - platform: rgb
    name: "${friendly_name} — Top LED"
    id: rgb_led
    red: output_red
    green: output_green
    blue: output_blue

output:
  - platform: esp8266_pwm
    id: output_red
    pin: D5
  - platform: esp8266_pwm
    id: output_green
    pin: D6
  - platform: esp8266_pwm
    id: output_blue
    pin: D7

sensor:
  - platform: uptime
    name: "${friendly_name} — Uptime"
  - platform: wifi_signal
    name: "${friendly_name} — Signal"
    update_interval: 60s
  - platform: bme280
    address: 0x76
    temperature:
      name: "${room} Temperature"
    pressure:
      name: "${room} Pressure"
    humidity:
      name: "${room} Humidity"
    update_interval: 60s
