esphome:
  name: lsc_smart_connect_node_bedroom
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

api:
logger:
ota:

binary_sensor:
  - platform: status
    name: "LSC Smart Connect Bedroom Status"

output:
  - platform: esp8266_pwm
    id: led
    pin:
      number: GPIO4
      inverted: true

light:
  - platform: monochromatic
    id: status_led
    name: "LSC Smart Connect Bedroom Light"
    output: led

switch:
  - platform: gpio
    id: relay
    pin: GPIO12
  - platform: template
    name: "LSC Smart Connect Bedroom Relay"
    optimistic: true
    id: relay_and_light
    turn_on_action:
      - switch.turn_on: relay
      - light.turn_on: status_led
    turn_off_action:
      - switch.turn_off: relay
      - light.turn_off: status_led

