esphome:
  name: lsc_smart_connect_switch
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

api:
logger:
ota:

binary_sensor:
  - platform: status
    name: "LSC Smart Connect Status"

switch:
  - platform: gpio
    name: "LSC Smart Connect Relay"
    pin: GPIO12
