esphome:
  name: nodemcu_env_sensor
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:
ota:
api:

i2c:
  scan: True

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "NodeMCU Environment Sensor IP address"
    ssid:
      name: "NodeMCU Environment Sensor SSID"
    bssid:
      name: "NodeMCU Environment Sensor BSSID"

sensor:
  - platform: wifi_signal
    name: "NodeMCU Environment Sensor WiFi Signal Sensor"
    update_interval: 60s

  - platform: bme280
    address: 0x76
    temperature:
      name: "NodeMCU Environment Sensor BME280 Temperature"
    pressure:
      name: "NodeMCU Environment Sensor BME280 Pressure"
    humidity:
      name: "NodeMCU Environment Sensor BME280 Humidity"
    update_interval: 60s
