esphome:
  name: nodemcu_environment_station
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:
ota:
api:

i2c:
  scan: True

binary_sensor:
  - platform: gpio
    pin: D6
    name: "nodemcu_environment_station PIR Sensor"
    device_class: motion

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "nodemcu_environment_station IP address"
    ssid:
      name: "nodemcu_environment_station SSID"
    # Disabled until new esphome update fixes this bug
    # https://github.com/esphome/issues/issues/137
    # bssid:
    #   name: "nodemcu_environment_station BSSID"

sensor:
  - platform: wifi_signal
    name: "nodemcu_environment_station WiFi Signal Sensor"
    update_interval: 60s

  - platform: bh1750
    name: "nodemcu_environment_station BH1750 Illuminance"
    update_interval: 60s

  - platform: bme280
    address: 0x76
    temperature:
      name: "nodemcu_environment_station BME280 temperature"
    pressure:
      name: "nodemcu_environment_station BME280 pressure"
    humidity:
      name: "nodemcu_environment_station BME280 humidity"
    update_interval: 60s
