esphome:
  name: nodemcu_environment_station
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:
ota:
api:

i2c:
  scan: True

sensor:
  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    update_interval: 60s

  - platform: bh1750
    name: "BH1750 Illuminance"
    update_interval: 60s

  - platform: bme280
    address: 0x76
    temperature:
      name: "BME280 temperature"
    pressure:
      name: "BME280 pressure"
    humidity:
      name: "BME280 humidity"
