esphome:
  name: nodemcu_downstairs
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:
ota:
api:

i2c:
  scan: True

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "nodemcu_downstairs IP address"
    ssid:
      name: "nodemcu_downstairs SSID"
    bssid:
      name: "nodemcu_downstairs BSSID"

sensor:
  - platform: wifi_signal
    name: "nodemcu_downstairs WiFi Signal Sensor"
    update_interval: 60s

  - platform: bme280
    address: 0x76
    temperature:
      name: "nodemcu_downstairs BME280 temperature"
    pressure:
      name: "nodemcu_downstairs BME280 pressure"
    humidity:
      name: "nodemcu_downstairs BME280 humidity"
    update_interval: 60s
