esphome:
  name: nodemcu_downstairs
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:
ota:
api:

sensor:
  - platform: wifi_signal
    name: "WiFi Signal Sensor Living Room"
    update_interval: 60s

  - platform: dht
    pin: D2
    model: DHT11
    temperature:
      name: "Living Room Temperature"
    humidity:
      name: "Living Room Humidity"
    update_interval: 60s
