esphome:
  name: nodemcu_downstairs
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:
ota:
api:

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "nodemcu_downstairs IP address"
    ssid:
      name: "nodemcu_downstairs SSID"
    # Disabled until new esphome update fixes this bug
    # https://github.com/esphome/issues/issues/137
    # bssid:
    #   name: "nodemcu_downstairs BSSID"

sensor:
  - platform: wifi_signal
    name: "nodemcu_downstairs WiFi Signal Sensor"
    update_interval: 60s

  - platform: dht
    pin: D2
    model: DHT11
    temperature:
      name: "nodemcu_downstairs Living Room Temperature"
    humidity:
      name: "nodemcu_downstairs Living Room Humidity"
    update_interval: 60s
