esphome:
  name: nodemcu_pir_test
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:
ota:
api:

binary_sensor:
  - platform: gpio
    pin: D2
    name: "PIR Sensor"
    device_class: motion
