esphome:
  name: "test"
  platform: ESP8266
  board: nodemcuv2

logger:

i2c:
  scan: True

sensor:
  - platform: hx711
    name: "HX711 Value"
    dout_pin: D5
    clk_pin: D6
    gain: 128
    update_interval: 2s
