esphome:
  name: wemos_sound_level_detector
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:
ota:
api:

sensor:
  - platform: adc
    pin: A0
    name: "Sound level"
    update_interval: 2s
    filters:
      - multiply: 3.3
