esphome:
  name: nodemcu_ws2812
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:
ota:
api:

light:
  - platform: fastled_clockless
    chipset: WS2812
    pin: GPIO23
    num_leds: 1
    name: "FastLED WS2811 Light"
