esphome:
  name: nodemcu_ws2812
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:
ota:
api:

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "WS8212 IP"
    ssid:
      name: "WS8212 SSID"
    bssid:
      name: "WS8212 BSSID"

sensor:
  - platform: wifi_signal
    name: "WS8212 Signal"
    update_interval: 60s

light:
  - platform: fastled_clockless
    name: "WS2812B 5M 30 IP30"
    chipset: WS2812B
    pin: D4
    rgb_order: GRB # Valid values are RGB, RBG, GRB, GBR, BRG and BGR. Defaults to RGB. GRB
    num_leds: 160
    effects:
      - addressable_rainbow:
      - addressable_color_wipe:
      - addressable_scan:
      - addressable_twinkle:
