- platform: rest
  name: "Slack status home office"
  resource: "https://slack.com/api/users.profile.set"
  method: "POST"
  headers:
    authorization: !secret slack_api_token
  data:
    profile: '{ "status_text": "Home Office, please do not disturb", "status_emoji": ":house_with_garden:", "status_expiration": 0 }'
- platform: rest
  name: "Slack status commuting"
  resource: "https://slack.com/api/users.profile.set"
  method: "POST"
  headers:
    authorization: !secret slack_api_token
  data:
    profile: '{ "status_text": "On the train", "status_emoji": ":train2:", "status_expiration": 0 }'
- platform: rest
  name: "Slack status at home"
  resource: "https://slack.com/api/users.profile.set"
  method: "POST"
  headers:
    authorization: !secret slack_api_token
  data:
    profile: '{ "status_text": "At home, do not message me", "status_emoji": ":no_entry_sign:", "status_expiration": 0 }'
- platform: rest
  name: "Slack status at work"
  resource: "https://slack.com/api/users.profile.set"
  method: "POST"
  headers:
    authorization: !secret slack_api_token
  data:
    profile: '{ "status_text": "", "status_emoji": "", "status_expiration": 0 }'

- platform: rest
  name: "Slack away"
  resource: "https://slack.com/api/users.setPresence"
  method: "POST"
  headers:
    authorization: !secret slack_api_token
  data:
    presence: 'away'
