homeassistant:
  customize:
    sensor.nzbget_article_cache:
      icon: mdi:cached
    sensor.nzbget_download_paused:
      icon: mdi:pause-circle
    sensor.nzbget_post_processing_paused:
      icon: mdi:pause-octagon
    sensor.nzbget_queue_size:
      icon: mdi:plus-box-multiple
    sensor.nzbget.size:
      icon: mdi:folder-zip
    sensor.nzbget_speed:
      icon: mdi:speedometer
    sensor.nzbget_uptime:
      icon: mdi:update

nzbget:
  host: !secret localhost
  username: !secret nzbget_username
  password: !secret nzbget_password
