homeassistant:
  customize:
    sensor.nzbget_article_cache:
      icon: mdi:cached
    sensor.nzbget_download_paused:
      icon: mdi:pause-circle
    sensor.nzbget_post_processing_paused:
      icon: mdi:pause-octagon
    sensor.nzbget_queue_size:
      icon: mdi:plus-box-multiple
    sensor.nzbget.size:
      icon: mdi:folder-zip
    sensor.nzbget_speed:
      icon: mdi:speedometer
    sensor.nzbget_uptime:
      icon: mdi:update

nzbget:
  host: !secret localhost
  username: !secret nzbget_username
  password: !secret nzbget_password

# sensor:
  # - platform: radarr_upcoming_media
  #   api_key: !secret radarr_api_key
  #   host: !secret localhost
  # - platform: radarr
  #   host: !secret localhost
  #   api_key: !secret radarr_api_key
  #   monitored_conditions:
  #     - movies
  #     - upcoming
  #     - status
  #   days: 5
  # - platform: sonarr_upcoming_media
  #   api_key: !secret sonarr_api_key
  #   host: !secret localhost
  # - platform: sonarr
  #   host: !secret localhost
  #   api_key: !secret sonarr_api_key
  #   monitored_conditions:
  #     - series
  #     - upcoming
  #     - wanted
  #   days: 5
