homeassistant:
  customize:
    plant.monstera_deliciosa:
      friendly_name: "Monstera Deliciosa"
      entity_picture: /local/monstera_bureau.jpg
    plant.ficus_elastica:
      friendly_name: "Ficus Elastica"
      entity_picture: /local/ficus_living.jpg


plant:
  ficus_elastica:
    sensors:
      battery: sensor.ficus_elastica_battery
      brightness: sensor.ficus_elastica_brightness
      conductivity: sensor.ficus_elastica_conductivity
      moisture: sensor.ficus_elastica_moisture
      temperature: sensor.ficus_elastica_temperature
    min_moisture: 14
    max_moisture: 30
    min_battery: 17
    min_conductivity: 50
    min_temperature: 18
  monstera_deliciosa:
    sensors:
      battery: sensor.monstera_deliciosa_battery
      brightness: sensor.monstera_deliciosa_brightness
      conductivity: sensor.monstera_deliciosa_conductivity
      moisture: sensor.monstera_deliciosa_moisture
      temperature: sensor.monstera_deliciosa_temperature
    min_moisture: 14
    max_moisture: 35
    min_battery: 17
    min_conductivity: 50
    min_temperature: 18
