homeassistant:
  customize:
    plant.monstera_deliciosa:
      friendly_name: "Monstera Deliciosa"
      entity_picture: /local/monstera_bureau.jpg
    plant.ficus_elastica:
      friendly_name: "Ficus Elastica"
      entity_picture: /local/ficus_living.jpg


plant:
  ficus_elastica:
    sensors:
      battery: sensor.ficus_elastica_living_battery_level
      brightness: sensor.ficus_elastica_living_illuminance
      moisture: sensor.ficus_elastica_living_moisture
      conductivity: sensor.ficus_elastica_living_soil_conductivity
      temperature: sensor.ficus_elastica_living_temperature
    min_moisture: 14
    max_moisture: 30
    min_battery: 17
    min_conductivity: 50
    min_temperature: 15

  monstera_deliciosa:
    sensors:
      battery: sensor.monstera_deliciosa_inkom_battery_level
      brightness: sensor.monstera_deliciosa_inkom_illuminance
      moisture: sensor.monstera_deliciosa_inkom_moisture
      conductivity: sensor.monstera_deliciosa_inkom_soil_conductivity
      temperature: sensor.monstera_deliciosa_inkom_temperature
    min_moisture: 14
    max_moisture: 35
    min_battery: 17
    min_conductivity: 50
    min_temperature: 18
