sensor:
  - platform: radarr_upcoming_media
    api_key: !secret radarr_api_key
    host: !secret localhost
  - platform: radarr
    host: !secret localhost
    api_key: !secret radarr_api_key
    monitored_conditions:
      - movies
      - upcoming
      - status
    days: 3


automation:
  - alias: "Radarr: download finished"
    trigger:
      - platform: webhook
        webhook_id: radarr-download-finished
    action:
      - service: persistent_notification.create
        data_template:
          title: "Radarr: download finished"
          message: >
            {{ trigger.json.remoteMovie.title }} - {{ trigger.json.remoteMovie.year }}
      - service: notify.thibault_devices
        data_template:
          title: "Radarr: download finished"
          message: >
            {{ trigger.json.remoteMovie.title }} - {{ trigger.json.remoteMovie.year }}
