homeassistant:
  customize:
    script.ha_reload_core:
      icon: mdi:reload
    script.ha_reload_automations:
      icon: mdi:robot
    script.ha_reload_scripts:
      icon: mdi:script-text
    script.ha_check_config:
      icon: mdi:check-decagram
    script.ha_restart:
      icon: mdi:restart

script:
  ha_reload_core:
    alias: "Quick reload core"
    sequence:
      - service: homeassistant.reload_core_config

  ha_reload_automations:
    alias: "Quick reload automations"
    sequence:
      - service: automation.reload

  ha_reload_scripts:
    alias: "Quick reload scripts"
    sequence:
      - service: script.reload

  ha_check_config:
    alias: "Check configuration"
    sequence:
      - service: homeassistant.check_config

  ha_restart:
    alias: "Restart Home Assistant"
    sequence:
      - service: homeassistant.restart
