sensor:
  - platform: sonarr_upcoming_media
    api_key: !secret sonarr_api_key
    host: !secret localhost
  - platform: sonarr
    host: !secret localhost
    api_key: !secret sonarr_api_key
    monitored_conditions:
      - series
      - upcoming
      - wanted
    days: 3

# automation:
#   - alias: "Sonarr: download finished"
#     trigger:
#       - platform: webhook
#         webhook_id: sonarr-download-finished
#     action:
#       - service: persistent_notification.create
#         data_template:
#           title: "Sonarr: download finished"
#           message: >
#             {{ trigger.json.remoteMovie.title }} - {{ trigger.json.remoteMovie.year }}
#       - service: notify.thibault_devices
#         data_template:
#           title: "Sonarr: downloaded {{ trigger.json.series.title }}"
#           message: >
#             {{ trigger.json.episodes[0].seasonNumber }}x{{ trigger.json.episodes[0].episodeNumber }} {{ trigger.json.episodes[0].title }}
