substitutions:
  device_name: "esp32_ble_monitor"
  friendly_name: "ESP32 BLE Monitor"
  plant_one: "Fridge 1"
  plant_two: "Fridge 2"

esphome:
  platform: ESP32
  board: esp32dev

packages:
  base_config: !include ../../common/base.yaml
  wifi: !include ../../common/wifi.yaml
  integrated: !include ../../common/integrated.yaml

esp32_ble_tracker:

sensor:
  - platform: xiaomi_hhccjcy01
    mac_address: 'C4:7C:8D:65:CA:76'
    temperature:
      name: "${plant_one} — Temperature"
    moisture:
      name: "${plant_one} — Moisture"
    illuminance:
      name: "${plant_one} — Illuminance"
    conductivity:
      name: "${plant_one} — Soil Conductivity"
    battery_level:
      name: "${plant_one} — Battery Level"

  - platform: xiaomi_hhccjcy01
    mac_address: 'C4:7C:8D:66:56:FC'
    temperature:
      name: "${plant_two} — Temperature"
    moisture:
      name: "${plant_two} — Moisture"
    illuminance:
      name: "${plant_two} — Illuminance"
    conductivity:
      name: "${plant_two} — Soil Conductivity"
    battery_level:
      name: "${plant_two} — Battery Level"
