name: CI Pipeline

on:
  push:
    branches:
      - master

jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repository
        uses: actions/checkout@v1
      - name: Running YAMLlint
        uses: "docker://pipelinecomponents/yamllint:latest"
        with:
          args: yamllint .

  esphome:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: ['3.x']
    steps:
      - name: Checking out repository
        uses: actions/checkout@master
      - name: "Setup Python: ${{ matrix.python_version }}"
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python_version }}
          architecture: x64
      - name: "Install ESPHome (via pip)"
        run: pip3 install esphome
      - name: Setup testing
        run: |
          cd esphome
          echo "wifi_ssid: home_wifi" > secrets.yaml
          echo "wifi_password: my_8_characters_long_key" >> secrets.yaml
          cat secrets.yaml
      - name: Compile (validate) ESPHome configs
        run: |
          cd esphome
          shopt -s globstar nullglob
          ESPHOME_CONFIGS=( **/*.yaml )
          esphome ${ESPHOME_CONFIGS[*]//secrets.yaml/} compile

  # home_assistant:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checking out repository
  #       uses: actions/checkout@master
  #     - name: Create secrets.yaml
  #       run: mv secrets.test.yaml secrets.yaml
  #     - name: "Validate with homeassistant/home-assistant:latest"
  #       uses: "docker://homeassistant/home-assistant:latest"
  #       with:
  #         args: python -m homeassistant --config . --script check_config --info all
  #     - name: "Validate with homeassistant/home-assistant:dev"
  #       uses: "docker://homeassistant/home-assistant:dev"
  #       continue-on-error: true
  #       with:
  #         args: python -m homeassistant --config . --script check_config --info all
