name: CI Pipeline

on:
  push:
    branches:
      - master

jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout
      - name: Run YAMLLint
        uses: "docker://pipelinecomponents/yamllint:latest"
        with:
          args: yamllint . 
