name: CI Pipeline

on:
  push:
    branches:
      - master

jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - name: Getting your configuration from GitHub
        uses: actions/checkout@v1
      - name: Running YAMLlint
        uses: "docker://pipelinecomponents/yamllint:latest"
        with:
          args: yamllint .
      # TODO: Validate ESPHome configs
      # TODO: Validate Home Assistant build: @latest
      # TODO: Validate Home Assistant build: @next
