name: CI Pipeline

on:
  push:
    branches:
      - master

jobs:
  linting:
    name: "Linting"
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@master
      - name: Superlint
        uses: github/super-linter@main
        env:
          VALIDATE_JAVASCRIPT_STANDARD: false
          VALIDATE_JAVASCRIPT_ES: false
          VALIDATE_JSCPD: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  esphome:
    name: "Compile ESPHome"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: ['3.x']
    steps:
      - name: "Checking out repository"
        uses: actions/checkout@master
      - name: "Setup Python: ${{ matrix.python_version }}"
        uses: actions/setup-python@master
        with:
          python-version: ${{ matrix.python_version }}
          architecture: x64
      - name: "Install ESPHome (via pip)"
        run: make dependencies
        working-directory: ./esphome
      - name: "Compile all configs"
        run: make test
        working-directory: ./esphome

  home_assistant:
    name: 'Validate HA config'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checking out repository'
        uses: actions/checkout@master
      - name: 'Create secrets.yaml'
        run: ./generate_secrets.sh
      - name: 'Stub Home Assistant files'
        run: |
          touch {customize,automations,scenes,scripts}.yaml
      - name: 'Remove HACS integrations'
        run: rm integrations/**/hacs_*.yaml
      - name: 'Validate HA config'
        uses: frenck/action-home-assistant@main
        with:
          secrets: ci_secrets.yaml
          version: stable

  home_assistant_beta:
    name: 'Validate HA config (Beta)'
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: 'Checking out repository'
        uses: actions/checkout@master
      - name: 'Create secrets.yaml'
        run: ./generate_secrets.sh
      - name: 'Stub Home Assistant files'
        run: |
          touch {customize,automations,scenes,scripts}.yaml
      - name: 'Remove HACS integrations'
        run: rm integrations/**/hacs_*.yaml
      - name: 'Validate HA config'
        uses: frenck/action-home-assistant@v1
        with:
          secrets: ci_secrets.yaml
          version: beta
