- platform: group
  name: "Thibault Devices"
  services:
    - service: mobile_app_thibault_maekelberghs_ipad
    - service: mobile_app_thibaults_iphone
    - service: mobile_app_thibaults_macbook_pro_itp
    - service: mobile_app_thibaults_macbook_pro

- platform: group
  name: "Lotte Devices"
  services:
    - service: mobile_app_ipad_van_lotte
    - service: mobile_app_lottes_iphone
